export const BROWSE_BACKING_INDEX = Object.freeze({
  "24k magic__bruno mars": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=aIpbroz-9CE",
    "videoId": "aIpbroz-9CE",
    "label": "24K Magic karaoke",
    "title": "Bruno Mars - 24k Magic (Official Karaoke Instrumental) | SongJam",
    "channelTitle": "Songjam: Official Karaoke",
    "durationSec": 240,
    "viewCount": 61997,
    "qualityScore": 126.37711202422211,
    "localFallback": null
  },
  "a whole new world__aladdin": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=CgHNvCUSSvg",
    "videoId": "CgHNvCUSSvg",
    "label": "A Whole New World karaoke",
    "title": "Aladdin | A Whole New World | Karaoke Duet",
    "channelTitle": "k-karaoke&more",
    "durationSec": 190,
    "viewCount": 6364578,
    "qualityScore": 116,
    "localFallback": null
  },
  "adorn__miguel": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=LNDY9LOX0KU",
    "videoId": "LNDY9LOX0KU",
    "label": "Adorn karaoke",
    "title": "Adorn in the Style of \"Miguel\" karaoke with lyrics (no lead vocal)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 205,
    "viewCount": 575027,
    "qualityScore": 123.2790647115074,
    "localFallback": null
  },
  "all of me__john legend": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=x9vVGaxxiyI",
    "videoId": "x9vVGaxxiyI",
    "label": "All of Me karaoke",
    "title": "All of Me - John Legend Karaoke 【With Guide Melody】 Instrumental",
    "channelTitle": "EdKara",
    "durationSec": 286,
    "viewCount": 18532029,
    "qualityScore": 120,
    "localFallback": null
  },
  "all star__smash mouth": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=Ye6e50mwG9E",
    "videoId": "Ye6e50mwG9E",
    "label": "All Star karaoke",
    "title": "Smash Mouth - All Star (Karaoke Version)",
    "channelTitle": "PARTY TYME KARAOKE CHANNEL",
    "durationSec": 219,
    "viewCount": 77338,
    "qualityScore": 112.66517881041848,
    "localFallback": null
  },
  "all that she wants__ace of base": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=dcKX-kOunmI",
    "videoId": "dcKX-kOunmI",
    "label": "All That She Wants karaoke",
    "title": "Ace of Base - All That She Wants (Karaoke Version)",
    "channelTitle": "PARTY TYME KARAOKE CHANNEL",
    "durationSec": 210,
    "viewCount": 58521,
    "qualityScore": 112.3019352160699,
    "localFallback": null
  },
  "always and forever__heatwave": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=j3ja-TJP6GQ",
    "videoId": "j3ja-TJP6GQ",
    "label": "Always and Forever karaoke",
    "title": "Heatwave - Always And Forever (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 229,
    "viewCount": 155080,
    "qualityScore": 121.57166737700553,
    "localFallback": null
  },
  "another one bites the dust__queen": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=MFrWqzTxpqE",
    "videoId": "MFrWqzTxpqE",
    "label": "Another One Bites the Dust karaoke",
    "title": "Another One Bites The Dust : Queen | Karaoke with Lyrics",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 215,
    "viewCount": 5555,
    "qualityScore": 117.23405218983066,
    "localFallback": null
  },
  "as it was__harry styles": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=QB3cbiTEd6M",
    "videoId": "QB3cbiTEd6M",
    "label": "As It Was karaoke",
    "title": "Harry Styles - As It Was (Official Karaoke Version with Backing Vocals & Lyrics)",
    "channelTitle": "King Karaoke Lyrics ",
    "durationSec": 184,
    "viewCount": 224,
    "qualityScore": 113.05074405500248,
    "localFallback": null
  },
  "baby one more time__britney spears": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=r6YH50RK0S0",
    "videoId": "r6YH50RK0S0",
    "label": "Baby One More Time karaoke",
    "title": "Britney Spears - Baby One More Time  [with backing vocals]- Karaoke/Lyrics",
    "channelTitle": "LyricVibe Karaoke",
    "durationSec": 249,
    "viewCount": 50678,
    "qualityScore": 120.1144584015405,
    "localFallback": null
  },
  "bad romance__lady gaga": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=xDAnYBvBnPw",
    "videoId": "xDAnYBvBnPw",
    "label": "Bad Romance karaoke",
    "title": "Bad Romance - Lady Gaga (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 328,
    "viewCount": 9401451,
    "qualityScore": 124,
    "localFallback": null
  },
  "barbie girl__aqua": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=qwBMZBnYdAY",
    "videoId": "qwBMZBnYdAY",
    "label": "Barbie Girl karaoke",
    "title": "Aqua - Barbie Girl (Karaoke Version) Lyrics",
    "channelTitle": "Karaoke Fun World",
    "durationSec": 228,
    "viewCount": 8051,
    "qualityScore": 117.71754947992696,
    "localFallback": null
  },
  "beat it__michael jackson": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=Mazh66SYsRk",
    "videoId": "Mazh66SYsRk",
    "label": "Beat It karaoke",
    "title": "Michael Jackson - Beat It (CC) 🎤 [Karaoke] [Instrumental]",
    "channelTitle": "CC Karaoke X",
    "durationSec": 307,
    "viewCount": 18529,
    "qualityScore": 124.80355594394682,
    "localFallback": null
  },
  "beauty and the beast__beauty and the beast": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=EijukRfXdNw",
    "videoId": "EijukRfXdNw",
    "label": "Beauty and the Beast karaoke",
    "title": "\"Home\" (Karaoke) – Beauty and the Beast | Lyrics on Screen",
    "channelTitle": "CurtainUp Karaoke",
    "durationSec": 198,
    "viewCount": 1128813,
    "qualityScore": 124,
    "localFallback": null
  },
  "before he cheats__carrie underwood": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=bLRSo2u0k5c",
    "videoId": "bLRSo2u0k5c",
    "label": "Before He Cheats karaoke",
    "title": "Before He Cheats - Carrie Underwood | KARAOKE WITH LYRICS",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 204,
    "viewCount": 5154,
    "qualityScore": 117.13643324264466,
    "localFallback": null
  },
  "believe__cher": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=s1DWvYZem_o",
    "videoId": "s1DWvYZem_o",
    "label": "Believe karaoke",
    "title": "Cher - Believe (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 247,
    "viewCount": 152957,
    "qualityScore": 121.55370807113061,
    "localFallback": null
  },
  "billie jean__michael jackson": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=fV2NqPSkWxg",
    "videoId": "fV2NqPSkWxg",
    "label": "Billie Jean karaoke",
    "title": "Billie Jean - Michael Jackson (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 321,
    "viewCount": 70402,
    "qualityScore": 120.54275499063483,
    "localFallback": null
  },
  "bless the broken road__rascal flatts": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=vwXMl5EqK-U",
    "videoId": "vwXMl5EqK-U",
    "label": "Bless the Broken Road karaoke",
    "title": "Rascal Flatts - Bless The Broken Road (Karaoke Version)",
    "channelTitle": "PARTY TYME KARAOKE CHANNEL",
    "durationSec": 246,
    "viewCount": 272886,
    "qualityScore": 114.30794376627634,
    "localFallback": null
  },
  "blinding lights__the weeknd": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=7aU_xOi2AjU",
    "videoId": "7aU_xOi2AjU",
    "label": "Blinding Lights karaoke",
    "title": "The Weeknd - Blinding Lights (Best Version) - Karaoke Instrumental Lyrics - ObsKure",
    "channelTitle": "ObsKure Karaoke",
    "durationSec": 201,
    "viewCount": 6314,
    "qualityScore": 131.40091373266858,
    "localFallback": null
  },
  "bohemian rhapsody__queen": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=yvEcMrstp80",
    "videoId": "yvEcMrstp80",
    "label": "Bohemian Rhapsody karaoke",
    "title": "Queen - Bohemian Rhapsody (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 365,
    "viewCount": 192373,
    "qualityScore": 121.8524323532012,
    "localFallback": null
  },
  "brown eyed girl__van morrison": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=SVdjV3o2cVc",
    "videoId": "SVdjV3o2cVc",
    "label": "Brown Eyed Girl karaoke",
    "title": "Van Morrison - Brown Eyed Girl (Karaoke Version) with Lyrics HD Vocal-Star Karaoke",
    "channelTitle": "Vocal Star Karaoke",
    "durationSec": 205,
    "viewCount": 9065,
    "qualityScore": 117.87210342529458,
    "localFallback": null
  },
  "bye bye bye__nsync": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=PEU9mi7HJsc",
    "videoId": "PEU9mi7HJsc",
    "label": "Bye Bye Bye karaoke",
    "title": "Bye Bye Bye in the Style of \"*NSYNC\" karaoke video with lyrics (no lead vocal)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 208,
    "viewCount": 819959,
    "qualityScore": 123.7413764113502,
    "localFallback": null
  },
  "can you feel the love tonight__the lion king": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=0li784rMk2Y",
    "videoId": "0li784rMk2Y",
    "label": "Can You Feel the Love Tonight karaoke",
    "title": "The Lion King - Can You Feel The Love Tonight (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 247,
    "viewCount": 176659,
    "qualityScore": 121.74140730319152,
    "localFallback": null
  },
  "celebration__kool and the gang": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=Cm_rQ1YUcsw",
    "videoId": "Cm_rQ1YUcsw",
    "label": "Celebration karaoke",
    "title": "Kool And The Gang - Celebration (Karaoke Version)",
    "channelTitle": "PARTY TYME KARAOKE CHANNEL",
    "durationSec": 303,
    "viewCount": 261004,
    "qualityScore": 114.24994148942423,
    "localFallback": null
  },
  "chandelier__sia": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=H-cCjyyWaLo",
    "videoId": "H-cCjyyWaLo",
    "label": "Chandelier karaoke",
    "title": "Sia - Chandelier (Official Instrumental + Lyrics on Screen / Karaoke)",
    "channelTitle": "Clawper Music",
    "durationSec": 217,
    "viewCount": 6118,
    "qualityScore": 121.35982841794598,
    "localFallback": null
  },
  "circle of life__the lion king": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=QL41lgDOQ9Q",
    "videoId": "QL41lgDOQ9Q",
    "label": "Circle of Life karaoke",
    "title": "LION KING - Circle of Life (KARAOKE) - Instrumental [Lyrics on screen, with backing vocals]",
    "channelTitle": "SerpentinePirate",
    "durationSec": 242,
    "viewCount": 949445,
    "qualityScore": 127.93240943521803,
    "localFallback": null
  },
  "come together__the beatles": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=_pzmjv9XPZg",
    "videoId": "_pzmjv9XPZg",
    "label": "Come Together karaoke",
    "title": "The Beatles - Come Together - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 257,
    "viewCount": 103573,
    "qualityScore": 113.045739667407,
    "localFallback": null
  },
  "complicated__avril lavigne": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=xNN372Ud0EE",
    "videoId": "xNN372Ud0EE",
    "label": "Complicated karaoke",
    "title": "Complicated - Avril Lavigne Karaoke 【No Guide Melody】 Instrumental",
    "channelTitle": "EdKara",
    "durationSec": 254,
    "viewCount": 4176923,
    "qualityScore": 120,
    "localFallback": null
  },
  "crazy in love__beyonce": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=YAUd0jOZomw",
    "videoId": "YAUd0jOZomw",
    "label": "Crazy in Love karaoke",
    "title": "Beyonce - Crazy In Love With Rapper - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 246,
    "viewCount": 19098,
    "qualityScore": 110.84296366701395,
    "localFallback": null
  },
  "crazy__gnarls barkley": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=nKDtXopqP9E",
    "videoId": "nKDtXopqP9E",
    "label": "Crazy karaoke",
    "title": "Gnarls Barkley - Crazy (Acoustic Guitar) | karaoke [Instrumental + Lyric]",
    "channelTitle": "Aline Lyrics",
    "durationSec": 235,
    "viewCount": 5528187,
    "qualityScore": 130,
    "localFallback": null
  },
  "creep__radiohead": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=ZFg3XnyILPk",
    "videoId": "ZFg3XnyILPk",
    "label": "Creep karaoke",
    "title": "Radiohead • Creep (CC Karaoke / Instrumental)",
    "channelTitle": "CC Karaoke",
    "durationSec": 245,
    "viewCount": 156163,
    "qualityScore": 127.58073443050674,
    "localFallback": null
  },
  "dance monkey__tones and i": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=FIixQedTVqE",
    "videoId": "FIixQedTVqE",
    "label": "Dance Monkey karaoke",
    "title": "Tones And I - Dance Monkey (Instrumental) (Karaoke Version)",
    "channelTitle": "ZZang KARAOKE",
    "durationSec": 221,
    "viewCount": 1300,
    "qualityScore": 101.34183005692051,
    "localFallback": null
  },
  "dancing queen__abba": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=k0XPbVLsW2Q",
    "videoId": "k0XPbVLsW2Q",
    "label": "Dancing Queen karaoke",
    "title": "Dancing Queen - ABBA | Karaoke Instrumental | Full Lyrics | Sing Along",
    "channelTitle": "Jokumuzik Karaoke",
    "durationSec": 219,
    "viewCount": 78451,
    "qualityScore": 134.68379545148258,
    "localFallback": null
  },
  "dog days are over__florence and the machine": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=wA3drzIZmO8",
    "videoId": "wA3drzIZmO8",
    "label": "Dog Days Are Over karaoke",
    "title": "Dog Days Are Over by Florence and the Machine - Karaoke with lyrics (no lead vocal)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 254,
    "viewCount": 1626273,
    "qualityScore": 124,
    "localFallback": null
  },
  "don t stop believin__journey": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=gzsSSqAN-jI",
    "videoId": "gzsSSqAN-jI",
    "label": "Don't Stop Believin' karaoke",
    "title": "Journey - Don't Stop Believin' (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 274,
    "viewCount": 301394,
    "qualityScore": 122.43740380704637,
    "localFallback": null
  },
  "don t stop me now__queen": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=5yebPm09eM0",
    "videoId": "5yebPm09eM0",
    "label": "Don't Stop Me Now karaoke",
    "title": "Queen - Don't Stop Me Now (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 229,
    "viewCount": 188422,
    "qualityScore": 121.82539482786729,
    "localFallback": null
  },
  "dont stop believin__journey": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=gzsSSqAN-jI",
    "videoId": "gzsSSqAN-jI",
    "label": "Dont Stop Believin karaoke",
    "title": "Journey - Don't Stop Believin' (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 274,
    "viewCount": 301394,
    "qualityScore": 111.43740380704637,
    "localFallback": null
  },
  "dont stop me now__queen": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=5yebPm09eM0",
    "videoId": "5yebPm09eM0",
    "label": "Dont Stop Me Now karaoke",
    "title": "Queen - Don't Stop Me Now (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 229,
    "viewCount": 188392,
    "qualityScore": 113.8251873700581,
    "localFallback": null
  },
  "dream on__aerosmith": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=x9Sy1jtmB7w",
    "videoId": "x9Sy1jtmB7w",
    "label": "Dream On karaoke",
    "title": "Aerosmith - Dream On (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 271,
    "viewCount": 178901,
    "qualityScore": 121.7578383044288,
    "localFallback": null
  },
  "dreams__fleetwood mac": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=WPt-FVlp2Pw",
    "videoId": "WPt-FVlp2Pw",
    "label": "Dreams karaoke",
    "title": "Dreams -  Fleetwood Mac (Lyrics Karaoke) [ goodkaraokesongs.com ]",
    "channelTitle": "Good Karaoke Songs",
    "durationSec": 274,
    "viewCount": 1517685,
    "qualityScore": 124,
    "localFallback": null
  },
  "drivers license__olivia rodrigo": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=F0CjrFhyskk",
    "videoId": "F0CjrFhyskk",
    "label": "drivers license karaoke",
    "title": "Olivia Rodrigo - Drivers License ( KARAOKE with BACKING VOCALS )",
    "channelTitle": "S T A R Karaoke KPH",
    "durationSec": 286,
    "viewCount": 1640842,
    "qualityScore": 116,
    "localFallback": null
  },
  "drops of jupiter__train": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=fjOrDT2ICrs",
    "videoId": "fjOrDT2ICrs",
    "label": "Drops of Jupiter karaoke",
    "title": "Train • Drops Of Jupiter (CC) 🎤 [Karaoke] [Instrumental Lyrics]",
    "channelTitle": "CC Karaoke",
    "durationSec": 262,
    "viewCount": 37542,
    "qualityScore": 133.7235522160835,
    "localFallback": null
  },
  "empire state of mind__jay z": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=52WbRVGAUBI",
    "videoId": "52WbRVGAUBI",
    "label": "Empire State of Mind karaoke",
    "title": "Empire State Of Mind - Jay-Z Feat Alicia Keys (Karaoke Version)",
    "channelTitle": "EasyKaraoke",
    "durationSec": 300,
    "viewCount": 1181080,
    "qualityScore": 116,
    "localFallback": null
  },
  "end of the road__boyz ii men": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=6aE4zVy4TS4",
    "videoId": "6aE4zVy4TS4",
    "label": "End of the Road karaoke",
    "title": "End Of The Road - Boyz II Men (KARAOKE PIANO - ORIGINAL KEY)",
    "channelTitle": "Karaoke Piano",
    "durationSec": 233,
    "viewCount": 95403,
    "qualityScore": 112.93868609464563,
    "localFallback": null
  },
  "endless love__diana ross and lionel richie": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=ZwhnQyVuL_4",
    "videoId": "ZwhnQyVuL_4",
    "label": "Endless Love karaoke",
    "title": "Lionel Richie & Diana Ross - Endless Love (Karaoke Version)",
    "channelTitle": "PARTY TYME KARAOKE CHANNEL",
    "durationSec": 264,
    "viewCount": 3636,
    "qualityScore": 108.68187162364978,
    "localFallback": null
  },
  "enter sandman__metallica": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=sMzAotfj6Cg",
    "videoId": "sMzAotfj6Cg",
    "label": "Enter Sandman karaoke",
    "title": "Enter Sandman - Metallica Karaoke",
    "channelTitle": "ARKaraoke85",
    "durationSec": 341,
    "viewCount": 870636,
    "qualityScore": 115.81950986261336,
    "localFallback": null
  },
  "every rose has its thorn__poison": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=Z3mg4Pcf_GI",
    "videoId": "Z3mg4Pcf_GI",
    "label": "Every Rose Has Its Thorn karaoke",
    "title": "Poison - Every Rose Has Its Thorn (Karaoke With Lyrics)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 258,
    "viewCount": 1532939,
    "qualityScore": 124,
    "localFallback": null
  },
  "eye of the tiger__survivor": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=p0Wu_MS7M1U",
    "videoId": "p0Wu_MS7M1U",
    "label": "Eye of the Tiger karaoke",
    "title": "Survivor - Eye of the Tiger (Rocky Soundtrack) - Karaoke Instrumental Lyrics - ObsKure",
    "channelTitle": "ObsKure Karaoke",
    "durationSec": 247,
    "viewCount": 24864,
    "qualityScore": 133.18671299136247,
    "localFallback": null
  },
  "faith__george michael": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=5pzfITUc53g",
    "videoId": "5pzfITUc53g",
    "label": "Faith karaoke",
    "title": "George Michael - Faith (Karaoke Version) with Lyrics HD Vocal-Star Karaoke",
    "channelTitle": "Vocal Star Karaoke",
    "durationSec": 197,
    "viewCount": 3974,
    "qualityScore": 116.79768358832139,
    "localFallback": null
  },
  "faithfully__journey": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=Kz2BS8Nk3Ho",
    "videoId": "Kz2BS8Nk3Ho",
    "label": "Faithfully karaoke",
    "title": "FAITHFULLY - Journey (HD Karaoke)",
    "channelTitle": "Atomic Karaoke... ",
    "durationSec": 268,
    "viewCount": 9656056,
    "qualityScore": 116,
    "localFallback": null
  },
  "firework__katy perry": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=mwBqXgljq7g",
    "videoId": "mwBqXgljq7g",
    "label": "Firework karaoke",
    "title": "Firework - Katy Perry (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 255,
    "viewCount": 834862,
    "qualityScore": 123.76484408181045,
    "localFallback": null
  },
  "flowers__miley cyrus": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=1OXCLEoq5sE",
    "videoId": "1OXCLEoq5sE",
    "label": "Flowers karaoke",
    "title": "FLOWERS - Miley Cyrus (KARAOKE)",
    "channelTitle": "Mi Balmz Karaoke Tracks",
    "durationSec": 211,
    "viewCount": 1030661,
    "qualityScore": 116,
    "localFallback": null
  },
  "friends in low places__garth brooks": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=wDzfoQIa_ZY",
    "videoId": "wDzfoQIa_ZY",
    "label": "Friends in Low Places karaoke",
    "title": "Friends In Low Places (Studio Version) in the Style of \"Garth Brooks\" karaoke lyrics (no lead vocal)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 225,
    "viewCount": 1830993,
    "qualityScore": 124,
    "localFallback": null
  },
  "genie in a bottle__christina aguilera": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=5STHOgJS-2Y",
    "videoId": "5STHOgJS-2Y",
    "label": "Genie in a Bottle karaoke",
    "title": "Christina Aguilera - Genie In A Bottle (Karaoke Version)",
    "channelTitle": "PARTY TYME KARAOKE CHANNEL",
    "durationSec": 247,
    "viewCount": 71116,
    "qualityScore": 112.55590196379164,
    "localFallback": null
  },
  "get lucky__daft punk": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=H22Y4XJZh_Y",
    "videoId": "H22Y4XJZh_Y",
    "label": "Get Lucky karaoke",
    "title": "Daft Punk - Get Lucky - Karaoke Instrumental",
    "channelTitle": "Karaoke Instrumental",
    "durationSec": 270,
    "viewCount": 904,
    "qualityScore": 120.86850529142609,
    "localFallback": null
  },
  "gin and juice__snoop dogg": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=Bx-nUUrhCKI",
    "videoId": "Bx-nUUrhCKI",
    "label": "Gin and Juice karaoke",
    "title": "Gin And Juice -  Snoop Dogg (Lyrics Karaoke) [ goodkaraokesongs.com ]",
    "channelTitle": "Good Karaoke Songs",
    "durationSec": 236,
    "viewCount": 150042,
    "qualityScore": 121.52863853346834,
    "localFallback": null
  },
  "girls just want to have fun__cyndi lauper": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=0kUuKhVDhjo",
    "videoId": "0kUuKhVDhjo",
    "label": "Girls Just Want to Have Fun karaoke",
    "title": "GIRLS JUST WANNA HAVE FUN / (KARAOKE) - Cyndi Lauper",
    "channelTitle": "TopHits Karaoke",
    "durationSec": 241,
    "viewCount": 1487572,
    "qualityScore": 110,
    "localFallback": null
  },
  "go your own way__fleetwood mac": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=fXQuQ08qPrA",
    "videoId": "fXQuQ08qPrA",
    "label": "Go Your Own Way karaoke",
    "title": "Go Your Own Way : Fleetwood Mac | Karaoke with Lyrics",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 251,
    "viewCount": 23616,
    "qualityScore": 119.11961902042884,
    "localFallback": null
  },
  "gold digger__kanye west": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=kdOkkmdyWGA",
    "videoId": "kdOkkmdyWGA",
    "label": "Gold Digger karaoke",
    "title": "Kanye West ft. Jamie Foxx - Gold Digger (Karaoke Version) with Lyrics HD Vocal-Star Karaoke",
    "channelTitle": "Vocal Star Karaoke",
    "durationSec": 205,
    "viewCount": 4570,
    "qualityScore": 116.97974860020955,
    "localFallback": null
  },
  "halo__beyonce": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=10usjS30T6o",
    "videoId": "10usjS30T6o",
    "label": "Halo karaoke",
    "title": "Beyonce - Halo (Karaoke Instrumental) with Lyrics",
    "channelTitle": "ThisSuxProductions",
    "durationSec": 263,
    "viewCount": 9915740,
    "qualityScore": 128,
    "localFallback": null
  },
  "hand in my pocket__alanis morissette": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=kQVrJKOgYF4",
    "videoId": "kQVrJKOgYF4",
    "label": "Hand in My Pocket karaoke",
    "title": "Hand In My Pocket in the Style of \"Alanis Morissette\" karaoke video with lyrics (no lead vocal)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 225,
    "viewCount": 416277,
    "qualityScore": 122.85814724816098,
    "localFallback": null
  },
  "hey jude__the beatles": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=laPSEoW0e5g",
    "videoId": "laPSEoW0e5g",
    "label": "Hey Jude karaoke",
    "title": "HEY JUDE - The Beatles (HQ KARAOKE VERSION with lyrics)",
    "channelTitle": "Agaw Music Karaoke",
    "durationSec": 419,
    "viewCount": 5155,
    "qualityScore": 117.1366860088586,
    "localFallback": null
  },
  "hey ya__outkast": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=h4hFqou-5CM",
    "videoId": "h4hFqou-5CM",
    "label": "Hey Ya karaoke",
    "title": "Hey Ya - Outkast (Karaoke/Lyrics/Instrumental)",
    "channelTitle": "Gangsta Karaoke (POWERED BY GTA_AND_PRECURE_FAN)",
    "durationSec": 246,
    "viewCount": 182,
    "qualityScore": 126.78021416395522,
    "localFallback": null
  },
  "hips dont lie__shakira": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=uQeW4wYhQUo",
    "videoId": "uQeW4wYhQUo",
    "label": "Hips Dont Lie karaoke",
    "title": "Shakira feat. Wyclef Jean - Hips Don't Lie (KARAOKE) [Instrumental with backing vocals]",
    "channelTitle": "KaraokeMedia",
    "durationSec": 225,
    "viewCount": 51579,
    "qualityScore": 115.13741875369122,
    "localFallback": null
  },
  "hit me with your best shot__pat benatar": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=YscRzIhuDLw",
    "videoId": "YscRzIhuDLw",
    "label": "Hit Me with Your Best Shot karaoke",
    "title": "Hit Me With Your Best Shot: Pat Benatar | Karaoke with lyrics (no lead vocal)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 172,
    "viewCount": 680435,
    "qualityScore": 123.49835993385125,
    "localFallback": null
  },
  "ho hey__the lumineers": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=sDmnZPAJ7j0",
    "videoId": "sDmnZPAJ7j0",
    "label": "Ho Hey karaoke",
    "title": "Ho Hey in the Style of \"The Lumineers\" karaoke video with lyrics (no lead vocal)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 170,
    "viewCount": 551282,
    "qualityScore": 123.22412143746885,
    "localFallback": null
  },
  "home__edward sharpe and the magnetic zeros": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=RMz0c70afBM",
    "videoId": "RMz0c70afBM",
    "label": "Home karaoke",
    "title": "Edward Sharpe and The Magnetic Zeros - Home - Karaoke Instrumental Lyrics - ObsKure",
    "channelTitle": "ObsKure Karaoke",
    "durationSec": 303,
    "viewCount": 345085,
    "qualityScore": 136.61377824595203,
    "localFallback": null
  },
  "hot in herre__nelly": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=zgyzGPrpPjQ",
    "videoId": "zgyzGPrpPjQ",
    "label": "Hot in Herre karaoke",
    "title": "Nelly - Hot In Herre - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 245,
    "viewCount": 27913,
    "qualityScore": 111.33741954673873,
    "localFallback": null
  },
  "hotel california__eagles": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=sSTjIvLIWu0",
    "videoId": "sSTjIvLIWu0",
    "label": "Hotel California karaoke",
    "title": "🎤 Eagles – Hotel California | Karaoke Version | Instrumental HQ | With Lyrics | No Vocals",
    "channelTitle": "Vocal Hero Karaoke Rock",
    "durationSec": 392,
    "viewCount": 169618,
    "qualityScore": 135.68841581414895,
    "localFallback": null
  },
  "how far ill go__moana": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=Bw9EfYysfD0",
    "videoId": "Bw9EfYysfD0",
    "label": "How Far Ill Go karaoke",
    "title": "HOW FAR I'LL GO Karaoke | Moana",
    "channelTitle": "STAR Kids Music",
    "durationSec": 161,
    "viewCount": 1014663,
    "qualityScore": 98,
    "localFallback": null
  },
  "i believe i can fly__r kelly": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=qaxkpihAGsE",
    "videoId": "qaxkpihAGsE",
    "label": "I Believe I Can Fly karaoke",
    "title": "I Believe I Can Fly: R. Kelly | Karaoke with lyrics",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 307,
    "viewCount": 7770191,
    "qualityScore": 124,
    "localFallback": null
  },
  "i dont want to miss a thing__aerosmith": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=NCS9Lp2_-2c",
    "videoId": "NCS9Lp2_-2c",
    "label": "I Dont Want to Miss a Thing karaoke",
    "title": "Aerosmith - I Don't Wanna Miss A Thing (Female Key - HD Piano Karaoke with Lyrics)",
    "channelTitle": "KaraoKeysPH",
    "durationSec": 302,
    "viewCount": 1457294,
    "qualityScore": 111,
    "localFallback": null
  },
  "i got you babe__sonny and cher": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=xm-oiJHg5Tk",
    "videoId": "xm-oiJHg5Tk",
    "label": "I Got You Babe karaoke",
    "title": "Sonny And Cher - I Got You Babe - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 205,
    "viewCount": 119874,
    "qualityScore": 113.23617499180723,
    "localFallback": null
  },
  "i gotta feeling__black eyed peas": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=-p37b8WhreI",
    "videoId": "-p37b8WhreI",
    "label": "I Gotta Feeling karaoke",
    "title": "Black Eyed Peas - I Gotta Feeling | With Lyrics HD Vocal-Star Karaoke",
    "channelTitle": "Vocal Star Karaoke",
    "durationSec": 261,
    "viewCount": 13937,
    "qualityScore": 118.432507900125,
    "localFallback": null
  },
  "i love rock n roll__joan jett": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=C3sGm6Jauuw",
    "videoId": "C3sGm6Jauuw",
    "label": "I Love Rock n Roll karaoke",
    "title": "I Love Rock 'n' Roll in the Style of \"Joan Jett & The Blackhearts\" karaoke lyrics (no lead vocal)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 187,
    "viewCount": 2291742,
    "qualityScore": 124,
    "localFallback": null
  },
  "i m yours__jason mraz": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=XhcCOmYRJeI",
    "videoId": "XhcCOmYRJeI",
    "label": "I'm Yours karaoke",
    "title": "Jason Mraz - I'm Yours - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 248,
    "viewCount": 70196,
    "qualityScore": 112.5389370959013,
    "localFallback": null
  },
  "i ve had the time of my life__bill medley and jennifer warnes": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=bPCNwfUxNKU",
    "videoId": "bPCNwfUxNKU",
    "label": "(I've Had) The Time of My Life karaoke",
    "title": "Bill Medley And Jennifer Warnes - (I've Had) The Time Of My Life - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 302,
    "viewCount": 84588,
    "qualityScore": 112.78192626984651,
    "localFallback": null
  },
  "i wanna dance with somebody__whitney houston": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=QMmc5ed_cgY",
    "videoId": "QMmc5ed_cgY",
    "label": "I Wanna Dance with Somebody karaoke",
    "title": "Whitney Houston - I Wanna Dance With Somebody (Karaoke Version)",
    "channelTitle": "PARTY TYME KARAOKE CHANNEL",
    "durationSec": 306,
    "viewCount": 170997,
    "qualityScore": 93.69896547337164,
    "localFallback": null
  },
  "i want it that way__backstreet boys": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=Jour9Cxc8xM",
    "videoId": "Jour9Cxc8xM",
    "label": "I Want It That Way karaoke",
    "title": "The Backstreet Boys - I Want It That Way (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 223,
    "viewCount": 127879,
    "qualityScore": 121.32039769443064,
    "localFallback": null
  },
  "i will always love you__whitney houston": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=6BXivcr9uvE",
    "videoId": "6BXivcr9uvE",
    "label": "I Will Always Love You karaoke",
    "title": "Whitney Houston - I Will Always Love You (Karaoke With Lyrics) @StingrayKaraoke",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 282,
    "viewCount": 442415,
    "qualityScore": 122.93748952966473,
    "localFallback": null
  },
  "i will survive__gloria gaynor": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=HwzIjdiNlhM",
    "videoId": "HwzIjdiNlhM",
    "label": "I Will Survive karaoke",
    "title": "Gloria Gaynor - I Will Survive (Karaoke with Lyrics)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 226,
    "viewCount": 1023762,
    "qualityScore": 124,
    "localFallback": null
  },
  "in da club__50 cent": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=G3vPA6D4wm4",
    "videoId": "G3vPA6D4wm4",
    "label": "In Da Club karaoke",
    "title": "In Da Club - 50 Cent (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 251,
    "viewCount": 20294,
    "qualityScore": 118.9221029681156,
    "localFallback": null
  },
  "ironic__alanis morissette": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=pkABRMfT0TE",
    "videoId": "pkABRMfT0TE",
    "label": "Ironic karaoke",
    "title": "Alanis Morissette - Ironic (Official Karaoke Instrumental) | SongJam",
    "channelTitle": "Songjam: Official Karaoke",
    "durationSec": 231,
    "viewCount": 11474,
    "qualityScore": 124.17914453663927,
    "localFallback": null
  },
  "irreplaceable__beyonce": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=f1-xS57-7EU",
    "videoId": "f1-xS57-7EU",
    "label": "Irreplaceable karaoke",
    "title": "Beyonce - Irreplaceable | Karaoke Lower Key",
    "channelTitle": "Karaoke Tracks Planet",
    "durationSec": 283,
    "viewCount": 30622,
    "qualityScore": 111.45810065646737,
    "localFallback": null
  },
  "islands in the stream__kenny rogers and dolly parton": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=OaXvO6MW7LY",
    "videoId": "OaXvO6MW7LY",
    "label": "Islands in the Stream karaoke",
    "title": "Kenny Rogers And Dolly Parton - Islands In The Stream (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 253,
    "viewCount": 341492,
    "qualityScore": 122.60014160226743,
    "localFallback": null
  },
  "jolene__dolly parton": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=j0_bxRdkEJ4",
    "videoId": "j0_bxRdkEJ4",
    "label": "Jolene karaoke",
    "title": "Jolene (LOWER -3) - Dolly Parton - Piano Karaoke Instrumental",
    "channelTitle": "Piano Karaoke",
    "durationSec": 180,
    "viewCount": 1491290,
    "qualityScore": 130,
    "localFallback": null
  },
  "killing me softly__fugees": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=Ad9VMFt1FDE",
    "videoId": "Ad9VMFt1FDE",
    "label": "Killing Me Softly karaoke",
    "title": "[MAGICSING Karaoke] FUGEES_KILLING ME SOFTLY karaoke | Tagalog",
    "channelTitle": "PH MAGICSING Karaoke",
    "durationSec": 284,
    "viewCount": 14781624,
    "qualityScore": 116,
    "localFallback": null
  },
  "kiss from a rose__seal": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=iAtOyCrZjCE",
    "videoId": "iAtOyCrZjCE",
    "label": "Kiss from a Rose karaoke",
    "title": "Seal - Kiss From a Rose - Karaoke Instrumental Lyrics - ObsKure",
    "channelTitle": "ObsKure Karaoke",
    "durationSec": 288,
    "viewCount": 12292,
    "qualityScore": 132.26886765475302,
    "localFallback": null
  },
  "landslide__fleetwood mac": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=TRH0o7fxP9E",
    "videoId": "TRH0o7fxP9E",
    "label": "Landslide karaoke",
    "title": "Landslide - Fleetwood Mac | Karaoke Version | KaraFun",
    "channelTitle": "KaraFun Karaoke",
    "durationSec": 221,
    "viewCount": 163323,
    "qualityScore": 113.63914204599901,
    "localFallback": null
  },
  "lean on me__bill withers": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=T4I9ieOArVQ",
    "videoId": "T4I9ieOArVQ",
    "label": "Lean on Me karaoke",
    "title": "Lean On Me - Bill Withers - Piano Karaoke Instrumental",
    "channelTitle": "Piano Karaoke",
    "durationSec": 241,
    "viewCount": 173674,
    "qualityScore": 127.71920442076961,
    "localFallback": null
  },
  "let it be__the beatles": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=SswjdoAAJb8",
    "videoId": "SswjdoAAJb8",
    "label": "Let It Be karaoke",
    "title": "The Beatles - Let It Be (Karaoke with Lyrics)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 258,
    "viewCount": 7729435,
    "qualityScore": 124,
    "localFallback": null
  },
  "let it go__frozen": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=RfmCVC3wFr4",
    "videoId": "RfmCVC3wFr4",
    "label": "Let It Go karaoke",
    "title": "\"Let It Go\" from Frozen: The Broadway Musical - Karaoke Track with Lyrics on Screen",
    "channelTitle": "CurtainUp Karaoke",
    "durationSec": 262,
    "viewCount": 315772,
    "qualityScore": 122.49812085341381,
    "localFallback": null
  },
  "lets get it on__marvin gaye": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=SXV-qD0xnB4",
    "videoId": "SXV-qD0xnB4",
    "label": "Lets Get It On karaoke",
    "title": "Marvin Gaye - Let's Get It On (Karaoke Version)",
    "channelTitle": "PARTY TYME KARAOKE CHANNEL",
    "durationSec": 275,
    "viewCount": 348788,
    "qualityScore": 103.62768460403876,
    "localFallback": null
  },
  "levitating__dua lipa": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=uHHfklqo3Ig",
    "videoId": "uHHfklqo3Ig",
    "label": "Levitating karaoke",
    "title": "Dua Lipa - Levitating (Official Karaoke Instrumental) | SongJam",
    "channelTitle": "Songjam: Official Karaoke",
    "durationSec": 216,
    "viewCount": 765202,
    "qualityScore": 129.65132828940227,
    "localFallback": null
  },
  "like a virgin__madonna": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=SE8R1FCbytw",
    "videoId": "SE8R1FCbytw",
    "label": "Like a Virgin karaoke",
    "title": "Madonna - Like A Virgin (Karaoke With Lyrics)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 230,
    "viewCount": 18455,
    "qualityScore": 118.79834214859503,
    "localFallback": null
  },
  "little talks__of monsters and men": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=wi35Z0qhKyA",
    "videoId": "wi35Z0qhKyA",
    "label": "Little Talks karaoke",
    "title": "Of Monsters And Men - Little Talks (Karaoke Version)",
    "channelTitle": "PARTY TYME KARAOKE CHANNEL",
    "durationSec": 275,
    "viewCount": 23542,
    "qualityScore": 111.11553006610009,
    "localFallback": null
  },
  "livin la vida loca__ricky martin": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=_inqd9G4sDs",
    "videoId": "_inqd9G4sDs",
    "label": "Livin La Vida Loca karaoke",
    "title": "Livin' la vida loca - Ricky Martin - Karaoke con coros",
    "channelTitle": "Karaoke Total Profesional",
    "durationSec": 246,
    "viewCount": 207816,
    "qualityScore": 113.95303694406495,
    "localFallback": null
  },
  "livin on a prayer__bon jovi": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=hzScwAhJY7s",
    "videoId": "hzScwAhJY7s",
    "label": "Livin on a Prayer karaoke",
    "title": "Bon Jovi - Livin' On A Prayer (Karaoke with Lyrics)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 259,
    "viewCount": 23243,
    "qualityScore": 119.09887654663162,
    "localFallback": null
  },
  "lose yourself__eminem": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=F-p2BQ4H1nA",
    "videoId": "F-p2BQ4H1nA",
    "label": "Lose Yourself karaoke",
    "title": "Lose Yourself - Eminem (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 329,
    "viewCount": 2729007,
    "qualityScore": 124,
    "localFallback": null
  },
  "losing my religion__rem": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=zMRULhgHBcE",
    "videoId": "zMRULhgHBcE",
    "label": "Losing My Religion karaoke",
    "title": "REM - Losing My Religion (Karaoke)",
    "channelTitle": "Best Original Karaoke",
    "durationSec": 270,
    "viewCount": 5157,
    "qualityScore": 109.13719139422014,
    "localFallback": null
  },
  "man i feel like a woman__shania twain": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=VwVuEZeM264",
    "videoId": "VwVuEZeM264",
    "label": "Man I Feel Like a Woman karaoke",
    "title": "Shania Twain - Man! I Feel Like A Woman (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 245,
    "viewCount": 175152,
    "qualityScore": 121.73024530222071,
    "localFallback": null
  },
  "man in the mirror__michael jackson": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=6fNoDBPfuyU",
    "videoId": "6fNoDBPfuyU",
    "label": "Man in the Mirror karaoke",
    "title": "Michael Jackson - Man In The Mirror (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 328,
    "viewCount": 144906,
    "qualityScore": 121.48325910492167,
    "localFallback": null
  },
  "mmmbop__hanson": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=o7qgLKM4Hc0",
    "videoId": "o7qgLKM4Hc0",
    "label": "MMMBop karaoke",
    "title": "Hanson - MMMBop (Karaoke Version) with Lyrics HD Vocal-Star Karaoke",
    "channelTitle": "Vocal Star Karaoke",
    "durationSec": 249,
    "viewCount": 3124,
    "qualityScore": 116.48413307561579,
    "localFallback": null
  },
  "mr brightside__the killers": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=rxbWx2d3bYM",
    "videoId": "rxbWx2d3bYM",
    "label": "Mr. Brightside karaoke",
    "title": "The Killers - Mr Brightside (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 233,
    "viewCount": 2619,
    "qualityScore": 116.2544064952757,
    "localFallback": null
  },
  "ms jackson__outkast": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=oReErpM6kQ0",
    "videoId": "oReErpM6kQ0",
    "label": "Ms Jackson karaoke",
    "title": "Ms. Jackson - Outkast (Karaoke Version)",
    "channelTitle": "EasyKaraoke",
    "durationSec": 256,
    "viewCount": 254922,
    "qualityScore": 114.21922195128394,
    "localFallback": null
  },
  "my girl__the temptations": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=9pe4JSIhXg0",
    "videoId": "9pe4JSIhXg0",
    "label": "My Girl karaoke",
    "title": "The Temptations - My Girl (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 177,
    "viewCount": 340741,
    "qualityScore": 122.59727318088369,
    "localFallback": null
  },
  "my heart will go on__celine dion": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=JZM4JVYX-zE",
    "videoId": "JZM4JVYX-zE",
    "label": "My Heart Will Go On karaoke",
    "title": "Celine Dion - My Heart Will Go On (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 285,
    "viewCount": 136752,
    "qualityScore": 121.40780105984518,
    "localFallback": null
  },
  "need you now__lady a": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=AX1I_Q4R1Zg",
    "videoId": "AX1I_Q4R1Zg",
    "label": "Need You Now karaoke",
    "title": "🎤 Lady Antebellum - Need You Now (Karaoke Lyrics)",
    "channelTitle": "King Of Karaoke",
    "durationSec": 246,
    "viewCount": 17948,
    "qualityScore": 118.7620481825831,
    "localFallback": null
  },
  "no diggity__blackstreet": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=JNeVf9rdPiM",
    "videoId": "JNeVf9rdPiM",
    "label": "No Diggity karaoke",
    "title": "Blackstreet (feat. Dr Dre) - No Diggity (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 275,
    "viewCount": 208517,
    "qualityScore": 121.95742440390376,
    "localFallback": null
  },
  "no scrubs__tlc": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=bUIvrsvm9z8",
    "videoId": "bUIvrsvm9z8",
    "label": "No Scrubs karaoke",
    "title": "TLC - No Scrubs (Karaoke Version)",
    "channelTitle": "PARTY TYME KARAOKE CHANNEL",
    "durationSec": 240,
    "viewCount": 144767,
    "qualityScore": 113.48200872388612,
    "localFallback": null
  },
  "nothing else matters__metallica": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=rIHcdAF9kBQ",
    "videoId": "rIHcdAF9kBQ",
    "label": "Nothing Else Matters karaoke",
    "title": "Metallica - Nothing else matters (Karaoke) [Instrumental]",
    "channelTitle": "KaraokeMedia",
    "durationSec": 415,
    "viewCount": 103575,
    "qualityScore": 127.045764825911,
    "localFallback": null
  },
  "november rain__guns n roses": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=KFUW0p50P58",
    "videoId": "KFUW0p50P58",
    "label": "November Rain karaoke",
    "title": "November Rain - Guns N' Roses (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 543,
    "viewCount": 5859742,
    "qualityScore": 124,
    "localFallback": null
  },
  "part of your world__the little mermaid": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=UFnmaM_bhnY",
    "videoId": "UFnmaM_bhnY",
    "label": "Part of Your World karaoke",
    "title": "[KARAOKE] The Little Mermaid - Part of your world",
    "channelTitle": "Humor Harbor",
    "durationSec": 187,
    "viewCount": 184644,
    "qualityScore": 103.79900559949913,
    "localFallback": null
  },
  "party rock anthem__lmfao": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=0WM9Amg7F5s",
    "videoId": "0WM9Amg7F5s",
    "label": "Party Rock Anthem karaoke",
    "title": "Party Rock Anthem in the Style of \"LMFAO\" karaoke video with lyrics (no lead vocal)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 264,
    "viewCount": 421217,
    "qualityScore": 122.87351767199337,
    "localFallback": null
  },
  "picture__kid rock": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=tuP6LczqLR4",
    "videoId": "tuP6LczqLR4",
    "label": "Picture karaoke",
    "title": "Kid Rock feat Sheryl Crow - Picture - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 304,
    "viewCount": 92155,
    "qualityScore": 112.89355671036903,
    "localFallback": null
  },
  "poker face__lady gaga": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=XMwNBEJKeXU",
    "videoId": "XMwNBEJKeXU",
    "label": "Poker Face karaoke",
    "title": "Poker Face - Lady Gaga (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 244,
    "viewCount": 108438,
    "qualityScore": 121.10554449693079,
    "localFallback": null
  },
  "proud mary__tina turner": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=NULJlWrjg2M",
    "videoId": "NULJlWrjg2M",
    "label": "Proud Mary karaoke",
    "title": "Tina Turner - Proud Mary (Official Karaoke Instrumental) | SongJam",
    "channelTitle": "Songjam: Official Karaoke",
    "durationSec": 287,
    "viewCount": 177456,
    "qualityScore": 127.74727206384608,
    "localFallback": null
  },
  "purple rain__prince": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=zXzOrEioBqA",
    "videoId": "zXzOrEioBqA",
    "label": "Purple Rain karaoke",
    "title": "Prince - Purple Rain (Karaoke Version) with Lyrics HD Vocal-Star Karaoke",
    "channelTitle": "Vocal Star Karaoke",
    "durationSec": 302,
    "viewCount": 64951,
    "qualityScore": 120.43775752586403,
    "localFallback": null
  },
  "quit playing games__backstreet boys": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=St4OFodlJhk",
    "videoId": "St4OFodlJhk",
    "label": "Quit Playing Games karaoke",
    "title": "Quit Playing Games (With My Heart) (Karaoke) - Backstreet Boys",
    "channelTitle": "KaraokeJP",
    "durationSec": 257,
    "viewCount": 271246,
    "qualityScore": 114.30009002740033,
    "localFallback": null
  },
  "rehab__amy winehouse": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=w42pSGRICag",
    "videoId": "w42pSGRICag",
    "label": "Rehab karaoke",
    "title": "Rehab in the style of Amy Winehouse karaoke video with lyrics",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 231,
    "viewCount": 4291994,
    "qualityScore": 124,
    "localFallback": null
  },
  "respect__aretha franklin": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=0GApz9a8vEk",
    "videoId": "0GApz9a8vEk",
    "label": "Respect karaoke",
    "title": "Aretha Franklin - Respect (Official Karaoke Instrumental) | SongJam",
    "channelTitle": "Songjam: Official Karaoke",
    "durationSec": 160,
    "viewCount": 134004,
    "qualityScore": 127.38135328655711,
    "localFallback": null
  },
  "rolling in the deep__adele": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=B3O1OlTWXSA",
    "videoId": "B3O1OlTWXSA",
    "label": "Rolling in the Deep karaoke",
    "title": "Rolling in The Deep - Adele (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 262,
    "viewCount": 26314389,
    "qualityScore": 124,
    "localFallback": null
  },
  "say my name__destiny s child": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=4Edx21WbZ5o",
    "videoId": "4Edx21WbZ5o",
    "label": "Say My Name karaoke",
    "title": "Say My Name - Destiny's Child (Karaoke Version)",
    "channelTitle": "EasyKaraoke",
    "durationSec": 288,
    "viewCount": 39435,
    "qualityScore": 111.78764553548613,
    "localFallback": null
  },
  "say you wont let go__james arthur": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=HYjZHF9cE5Q",
    "videoId": "HYjZHF9cE5Q",
    "label": "Say You Wont Let Go karaoke",
    "title": "Say You Won't Let Go - James Arthur (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 242,
    "viewCount": 2908876,
    "qualityScore": 118,
    "localFallback": null
  },
  "september__earth wind and fire": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=V81sR30RPU8",
    "videoId": "V81sR30RPU8",
    "label": "September karaoke",
    "title": "September in the Style of \"Earth, Wind & Fire\" karaoke video with lyrics (no lead vocal)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 227,
    "viewCount": 225639,
    "qualityScore": 122.06024249897848,
    "localFallback": null
  },
  "shake it off__taylor swift": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=tCqNQdQDyU4",
    "videoId": "tCqNQdQDyU4",
    "label": "Shake It Off karaoke",
    "title": "Shake It Off - Taylor Swift (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 248,
    "viewCount": 1220151,
    "qualityScore": 124,
    "localFallback": null
  },
  "shallow__lady gaga": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=pOp3ZwUhLjU",
    "videoId": "pOp3ZwUhLjU",
    "label": "Shallow karaoke",
    "title": "Lady Gaga and Bradley Cooper - Shallow (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 219,
    "viewCount": 238563,
    "qualityScore": 122.1328092625729,
    "localFallback": null
  },
  "since u been gone__kelly clarkson": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=U-NM10P2_X0",
    "videoId": "U-NM10P2_X0",
    "label": "Since U Been Gone karaoke",
    "title": "Kelly Clarkson - Since U Been Gone (Karaoke Version)",
    "channelTitle": "PARTY TYME KARAOKE CHANNEL",
    "durationSec": 220,
    "viewCount": 30646,
    "qualityScore": 111.4591213917385,
    "localFallback": null
  },
  "single ladies__beyonce": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=rzJHdIWOYtg",
    "videoId": "rzJHdIWOYtg",
    "label": "Single Ladies karaoke",
    "title": "Beyonce - Single ladies (Karaoke version) official lyrics",
    "channelTitle": "Lyrics Music",
    "durationSec": 204,
    "viewCount": 78934,
    "qualityScore": 120.69179233403034,
    "localFallback": null
  },
  "sk8er boi__avril lavigne": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=eAgqlIoXh08",
    "videoId": "eAgqlIoXh08",
    "label": "Sk8er Boi karaoke",
    "title": "Avril Lavigne - Sk8er Boi (Karaoke)",
    "channelTitle": "KaraokeOnVEVO",
    "durationSec": 213,
    "viewCount": 399751,
    "qualityScore": 114.80536867649639,
    "localFallback": null
  },
  "slow jamz__twista": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=UaIvqrLCtSY",
    "videoId": "UaIvqrLCtSY",
    "label": "Slow Jamz karaoke",
    "title": "Slow Jamz - Twista (Karaoke Version)",
    "channelTitle": "EasyKaraoke",
    "durationSec": 202,
    "viewCount": 28740,
    "qualityScore": 111.37546029139462,
    "localFallback": null
  },
  "smooth__santana": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=rnEVEz2ULSQ",
    "videoId": "rnEVEz2ULSQ",
    "label": "Smooth karaoke",
    "title": "Smooth (KARAOKE) | Santana",
    "channelTitle": "Pinoy Karaoke Battle",
    "durationSec": 318,
    "viewCount": 749421,
    "qualityScore": 115.62417757570623,
    "localFallback": null
  },
  "somebody that i used to know__gotye": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=BmgzY2R2NBc",
    "videoId": "BmgzY2R2NBc",
    "label": "Somebody That I Used to Know karaoke",
    "title": "Gotye Feat. Kimbra - Somebody That I Used To Know - Duet Karaoke Instrumental Lyrics - ObsKure",
    "channelTitle": "ObsKure Karaoke",
    "durationSec": 246,
    "viewCount": 162571,
    "qualityScore": 135.63312923146347,
    "localFallback": null
  },
  "somebody to love__queen": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=WWJmz0LTifE",
    "videoId": "WWJmz0LTifE",
    "label": "Somebody to Love karaoke",
    "title": "Somebody To Love -  Queen (Lyrics Karaoke) [ goodkaraokesongs.com ]",
    "channelTitle": "Good Karaoke Songs",
    "durationSec": 306,
    "viewCount": 3547351,
    "qualityScore": 124,
    "localFallback": null
  },
  "someone like you__adele": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=rMSQwIp4Jg8",
    "videoId": "rMSQwIp4Jg8",
    "label": "Someone Like You karaoke",
    "title": "Someone Like You - Adele (Karaoke Songs With Lyrics)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 296,
    "viewCount": 47508360,
    "qualityScore": 124,
    "localFallback": null
  },
  "stand by me__ben e king": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=Ve5tKGh1t8o",
    "videoId": "Ve5tKGh1t8o",
    "label": "Stand by Me karaoke",
    "title": "Ben E. King - Stand By Me (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 187,
    "viewCount": 251221,
    "qualityScore": 122.2001678200393,
    "localFallback": null
  },
  "stay with me__sam smith": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=VEATNpwLSZo",
    "videoId": "VEATNpwLSZo",
    "label": "Stay With Me karaoke",
    "title": "Stay With Me - Sam Smith - Piano Karaoke Instrumental",
    "channelTitle": "Piano Karaoke",
    "durationSec": 174,
    "viewCount": 1091767,
    "qualityScore": 130,
    "localFallback": null
  },
  "stayin alive__bee gees": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=CkqOJk-GHf8",
    "videoId": "CkqOJk-GHf8",
    "label": "Stayin' Alive karaoke",
    "title": "Bee Gees - Stayin' Alive | With Lyrics HD Vocal-Star Karaoke",
    "channelTitle": "Vocal Star Karaoke",
    "durationSec": 299,
    "viewCount": 32685,
    "qualityScore": 99.54304546790581,
    "localFallback": null
  },
  "summer of 69__bryan adams": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=gnbg4nXM4Cg",
    "videoId": "gnbg4nXM4Cg",
    "label": "Summer of 69 karaoke",
    "title": "Summer of ’69 – Bryan Adams (Karaoke Version)",
    "channelTitle": "Dadidu Karaoke",
    "durationSec": 238,
    "viewCount": 1990,
    "qualityScore": 107.89655922922913,
    "localFallback": null
  },
  "sweet caroline__neil diamond": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=4Vgstvv3u1M",
    "videoId": "4Vgstvv3u1M",
    "label": "Sweet Caroline karaoke",
    "title": "Neil Diamond - Sweet Caroline (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 238,
    "viewCount": 184840,
    "qualityScore": 121.80038787954,
    "localFallback": null
  },
  "sweet child o mine__guns n roses": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=TBxAAOOJzL8",
    "videoId": "TBxAAOOJzL8",
    "label": "Sweet Child O' Mine karaoke",
    "title": "Sweet Child O' Mine - Guns N' Roses (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 367,
    "viewCount": 3869162,
    "qualityScore": 124,
    "localFallback": null
  },
  "sweet dreams are made of this__eurythmics": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=OBIHNRtZeW8",
    "videoId": "OBIHNRtZeW8",
    "label": "Sweet Dreams (Are Made of This) karaoke",
    "title": "Eurythmics - Sweet Dreams Are Made Of This (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 224,
    "viewCount": 220437,
    "qualityScore": 122.02985347580946,
    "localFallback": null
  },
  "sweet home alabama__lynyrd skynyrd": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=c7kOCtBGY9E",
    "videoId": "c7kOCtBGY9E",
    "label": "Sweet Home Alabama karaoke",
    "title": "Sweet Home Alabama in the Style of \"Lynyrd Skynyrd\" karaoke video with lyrics (no lead vocal)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 303,
    "viewCount": 446560,
    "qualityScore": 122.94963945743368,
    "localFallback": null
  },
  "take me home country roads__john denver": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=NzLTH93B620",
    "videoId": "NzLTH93B620",
    "label": "Take Me Home Country Roads karaoke",
    "title": "John Denver - Take Me Home, Country Roads (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 197,
    "viewCount": 193484,
    "qualityScore": 121.85993517164601,
    "localFallback": null
  },
  "take me out__franz ferdinand": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=S92z82e0cwY",
    "videoId": "S92z82e0cwY",
    "label": "Take Me Out karaoke",
    "title": "Take Me Out in the style of Franz Ferdinand | Karaoke with Lyrics",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 251,
    "viewCount": 9493,
    "qualityScore": 117.9322104426203,
    "localFallback": null
  },
  "take my breath away__berlin": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=4YgfU1BNAeU",
    "videoId": "4YgfU1BNAeU",
    "label": "Take My Breath Away karaoke",
    "title": "Berlin - Take My Breath Away (Karaoke & Lyrics)",
    "channelTitle": "Let's Sing Karaoke",
    "durationSec": 265,
    "viewCount": 38130,
    "qualityScore": 119.74380041582101,
    "localFallback": null
  },
  "take on me__a ha": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=GK0hisiU6-c",
    "videoId": "GK0hisiU6-c",
    "label": "Take On Me karaoke",
    "title": "A-Ha - Take On Me (Official Karaoke Instrumental) | SongJam",
    "channelTitle": "Songjam: Official Karaoke",
    "durationSec": 215,
    "viewCount": 168865,
    "qualityScore": 127.68261893304673,
    "localFallback": null
  },
  "tennessee whiskey__chris stapleton": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=AScdyDHCdSE",
    "videoId": "AScdyDHCdSE",
    "label": "Tennessee Whiskey karaoke",
    "title": "Chris Stapleton - Tennessee Whiskey (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 297,
    "viewCount": 264608,
    "qualityScore": 122.2678089107487,
    "localFallback": null
  },
  "the middle__jimmy eat world": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=k2zvWg0516Q",
    "videoId": "k2zvWg0516Q",
    "label": "The Middle karaoke",
    "title": "Jimmy Eat World - The Middle - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 179,
    "viewCount": 15926,
    "qualityScore": 110.60632013417072,
    "localFallback": null
  },
  "the scientist__coldplay": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=inhK1WbEbpg",
    "videoId": "inhK1WbEbpg",
    "label": "The Scientist karaoke",
    "title": "Coldplay • The Scientist (CC Karaoke / Instrumental)",
    "channelTitle": "CC Karaoke",
    "durationSec": 309,
    "viewCount": 227701,
    "qualityScore": 128.0720948137628,
    "localFallback": null
  },
  "thinking out loud__ed sheeran": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=wsfOZehhML8",
    "videoId": "wsfOZehhML8",
    "label": "Thinking Out Loud karaoke",
    "title": "Thinking Out Loud - Ed Sheeran Karaoke 【No Guide Melody】 Instrumental",
    "channelTitle": "EdKara",
    "durationSec": 287,
    "viewCount": 2899346,
    "qualityScore": 120,
    "localFallback": null
  },
  "timber__pitbull": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=G0wo1sEaeko",
    "videoId": "G0wo1sEaeko",
    "label": "Timber karaoke",
    "title": "Pitbull and Ke$ha Timber Karaoke lyrics",
    "channelTitle": "KJBill.com",
    "durationSec": 222,
    "viewCount": 382039,
    "qualityScore": 112.74632309884174,
    "localFallback": null
  },
  "time of my life__bill medley and jennifer warnes": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=bPCNwfUxNKU",
    "videoId": "bPCNwfUxNKU",
    "label": "Time of My Life karaoke",
    "title": "Bill Medley And Jennifer Warnes - (I've Had) The Time Of My Life - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 302,
    "viewCount": 84588,
    "qualityScore": 112.78192626984651,
    "localFallback": null
  },
  "titanium__david guetta": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=eJb4XybuGSg",
    "videoId": "eJb4XybuGSg",
    "label": "Titanium karaoke",
    "title": "Titanium ft. Sia - David Guetta Karaoke 【With Guide Melody】 Instrumental",
    "channelTitle": "EdKara",
    "durationSec": 240,
    "viewCount": 17211016,
    "qualityScore": 120,
    "localFallback": null
  },
  "torn__natalie imbruglia": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=xAFnrql49oU",
    "videoId": "xAFnrql49oU",
    "label": "Torn karaoke",
    "title": "TORN - Natalie Imbruglia (HD Karaoke)",
    "channelTitle": "Atomic Karaoke... ",
    "durationSec": 230,
    "viewCount": 818692,
    "qualityScore": 115.7393616398648,
    "localFallback": null
  },
  "total eclipse of the heart__bonnie tyler": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=pnJRZU4oAi8",
    "videoId": "pnJRZU4oAi8",
    "label": "Total Eclipse of the Heart karaoke",
    "title": "Bonnie Tyler - Total Eclipse of the Heart (Karaoke With Lyrics)",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 337,
    "viewCount": 28834725,
    "qualityScore": 124,
    "localFallback": null
  },
  "umbrella__rihanna": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=xCJtwKRysQU",
    "videoId": "xCJtwKRysQU",
    "label": "Umbrella karaoke",
    "title": "Umbrella - Rihanna (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 291,
    "viewCount": 9312881,
    "qualityScore": 124,
    "localFallback": null
  },
  "unbreak my heart__toni braxton": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=lV_XW93fZ-A",
    "videoId": "lV_XW93fZ-A",
    "label": "Unbreak My Heart karaoke",
    "title": "Toni Braxton - Unbreak My Heart - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 275,
    "viewCount": 41115,
    "qualityScore": 111.84200088378554,
    "localFallback": null
  },
  "unchained melody__the righteous brothers": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=XsVWMM2CO0U",
    "videoId": "XsVWMM2CO0U",
    "label": "Unchained Melody karaoke",
    "title": "Righteous Brothers - Unchained Melody (Karaoke & Lyrics)",
    "channelTitle": "Let's Sing Karaoke",
    "durationSec": 234,
    "viewCount": 11641159,
    "qualityScore": 124,
    "localFallback": null
  },
  "under pressure__queen and david bowie": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=AlbDIxCha6s",
    "videoId": "AlbDIxCha6s",
    "label": "Under Pressure karaoke",
    "title": "Under Pressure : Queen & David Bowie | Karaoke with Lyrics",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 240,
    "viewCount": 5737,
    "qualityScore": 117.27605454964733,
    "localFallback": null
  },
  "under the bridge__red hot chili peppers": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=-0eMBII6JC0",
    "videoId": "-0eMBII6JC0",
    "label": "Under the Bridge karaoke",
    "title": "Red Hot Chili Peppers • Under The Bridge (CC Karaoke / Instrumental)",
    "channelTitle": "CC Karaoke",
    "durationSec": 269,
    "viewCount": 260806,
    "qualityScore": 128.24895273514727,
    "localFallback": null
  },
  "uptown funk__bruno mars": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=F3R6eJKAz4M",
    "videoId": "F3R6eJKAz4M",
    "label": "Uptown Funk karaoke",
    "title": "Uptown Funk - Mark Ronson ft. Bruno Mars (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 301,
    "viewCount": 927128,
    "qualityScore": 123.90141909193552,
    "localFallback": null
  },
  "use somebody__kings of leon": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=ViZaNOsPf78",
    "videoId": "ViZaNOsPf78",
    "label": "Use Somebody karaoke",
    "title": "Use Somebody - Kings of Leon - Piano Karaoke Instrumental",
    "channelTitle": "Piano Karaoke",
    "durationSec": 219,
    "viewCount": 708791,
    "qualityScore": 129.55155458314735,
    "localFallback": null
  },
  "valerie__amy winehouse": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=jknvd7RMPQ4",
    "videoId": "jknvd7RMPQ4",
    "label": "Valerie karaoke",
    "title": "Valerie - Amy Winehouse (Acoustic Soulful Karaoke | Original Key)",
    "channelTitle": "Sam Backing Tracks",
    "durationSec": 249,
    "viewCount": 229070,
    "qualityScore": 114.07990464747772,
    "localFallback": null
  },
  "viva la vida__coldplay": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=_mE0Mx0LL-0",
    "videoId": "_mE0Mx0LL-0",
    "label": "Viva La Vida karaoke",
    "title": "Coldplay • Viva La Vida (CC Karaoke / Instrumental)",
    "channelTitle": "CC Karaoke",
    "durationSec": 247,
    "viewCount": 43148,
    "qualityScore": 125.90488201018192,
    "localFallback": null
  },
  "wagon wheel__darius rucker": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=X3DnqOWxPq4",
    "videoId": "X3DnqOWxPq4",
    "label": "Wagon Wheel karaoke",
    "title": "Darius Rucker - Wagon Wheel - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 278,
    "viewCount": 79449,
    "qualityScore": 112.70026530574228,
    "localFallback": null
  },
  "wannabe__spice girls": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=DO1XCUjxrRk",
    "videoId": "DO1XCUjxrRk",
    "label": "Wannabe karaoke",
    "title": "The Spice Girls - Wannabe - Karaoke Version from Zoom Karaoke",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 183,
    "viewCount": 49878,
    "qualityScore": 112.09372709265662,
    "localFallback": null
  },
  "wanted dead or alive__bon jovi": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=zNDT0SdLPF4",
    "videoId": "zNDT0SdLPF4",
    "label": "Wanted Dead or Alive karaoke",
    "title": "Wanted Dead Or Alive : Bon Jovi | Karaoke with Lyrics",
    "channelTitle": "Stingray Karaoke",
    "durationSec": 303,
    "viewCount": 16445,
    "qualityScore": 98.64810163345602,
    "localFallback": null
  },
  "waterfalls__tlc": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=gbRY7m0ZjqU",
    "videoId": "gbRY7m0ZjqU",
    "label": "Waterfalls karaoke",
    "title": "Waterfalls - TLC (KARAOKE)",
    "channelTitle": "MrEntertainerKaraoke",
    "durationSec": 321,
    "viewCount": 3370,
    "qualityScore": 108.58288970261401,
    "localFallback": null
  },
  "watermelon sugar__harry styles": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=LKgwC9Rr2VM",
    "videoId": "LKgwC9Rr2VM",
    "label": "Watermelon Sugar karaoke",
    "title": "Watermelon Sugar - Harry Styles (Karaoke Songs With Lyrics - Original Key)",
    "channelTitle": "Musisi Karaoke",
    "durationSec": 207,
    "viewCount": 20811,
    "qualityScore": 118.95487884765758,
    "localFallback": null
  },
  "with or without you__u2": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=baxtt8PEqsE",
    "videoId": "baxtt8PEqsE",
    "label": "With or Without You karaoke",
    "title": "U2 - With Or Without You - Instrumental Karaoke Version",
    "channelTitle": "Andrey Lednev",
    "durationSec": 295,
    "viewCount": 50244,
    "qualityScore": 116.10325262081656,
    "localFallback": null
  },
  "wonderful tonight__eric clapton": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=9H-Z-6ehH9s",
    "videoId": "9H-Z-6ehH9s",
    "label": "Wonderful Tonight karaoke",
    "title": "Eric Clapton - Wonderful Tonight (Karaoke Version) with Lyrics On Screen",
    "channelTitle": "Zoom Karaoke Official",
    "durationSec": 223,
    "viewCount": 213248,
    "qualityScore": 121.98665490015591,
    "localFallback": null
  },
  "wonderwall__oasis": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=I4RwbQ9zUEU",
    "videoId": "I4RwbQ9zUEU",
    "label": "Wonderwall karaoke",
    "title": "Oasis • Wonderwall (CC) 🎤 [Karaoke] [Instrumental Lyrics]",
    "channelTitle": "CC Karaoke",
    "durationSec": 261,
    "viewCount": 229838,
    "qualityScore": 136.08426550159425,
    "localFallback": null
  },
  "yeah__usher": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=1GdGtC3szvs",
    "videoId": "1GdGtC3szvs",
    "label": "Yeah! karaoke",
    "title": "Usher - Yeah (Karaoke & Lyrics)",
    "channelTitle": "Let's Sing Karaoke",
    "durationSec": 257,
    "viewCount": 86432,
    "qualityScore": 120.81002368752208,
    "localFallback": null
  },
  "yellow__coldplay": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=1Fv5IVf9KAc",
    "videoId": "1Fv5IVf9KAc",
    "label": "Yellow karaoke",
    "title": "Coldplay • Yellow (CC) 🎤 [Karaoke] [Instrumental Lyrics]",
    "channelTitle": "CC Karaoke",
    "durationSec": 268,
    "viewCount": 5293843,
    "qualityScore": 138,
    "localFallback": null
  },
  "you belong with me__taylor swift": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=dLzwCfw2BZc",
    "videoId": "dLzwCfw2BZc",
    "label": "You Belong with Me karaoke",
    "title": "You Belong with Me - Taylor Swift | Karaoke Version with Lyrics (Instrumental)",
    "channelTitle": "Mi Balmz Karaoke Tracks",
    "durationSec": 239,
    "viewCount": 1105615,
    "qualityScore": 138,
    "localFallback": null
  },
  "you shook me all night long__ac dc": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=R5VVEo0PtHg",
    "videoId": "R5VVEo0PtHg",
    "label": "You Shook Me All Night Long karaoke",
    "title": "AC/DC - You Shook Me All Night Long (Karaoke Version)",
    "channelTitle": "Vocal Star Karaoke",
    "durationSec": 229,
    "viewCount": 9332,
    "qualityScore": 109.90992419036515,
    "localFallback": null
  },
  "youll be in my heart__tarzan": {
    "approved": true,
    "playable": true,
    "embeddable": true,
    "trackSource": "youtube",
    "mediaUrl": "https://www.youtube.com/watch?v=rCzdVUCHvNc",
    "videoId": "rCzdVUCHvNc",
    "label": "Youll Be in My Heart karaoke",
    "title": "You'll Be In My Heart - Karaoke W/Lyrics (HQ) Slow version",
    "channelTitle": "DisneyKaraoke1",
    "durationSec": 178,
    "viewCount": 353385,
    "qualityScore": 98.64474433368301,
    "localFallback": null
  },
});
