export const emoji = (...codePoints) => String.fromCodePoint(...codePoints);

export const EMOJI = {
    fire: emoji(0x1F525),
    heart: emoji(0x2764, 0xFE0F),
    clap: emoji(0x1F44F),
    drink: emoji(0x1F37B),
    rocket: emoji(0x1F680),
    diamond: emoji(0x1F48E),
    crown: emoji(0x1F451),
    money: emoji(0x1F4B0),
    cherryBlossom: emoji(0x1F338),
    sparkle: emoji(0x2728),
    mic: emoji(0x1F3A4),
    radio: emoji(0x1F4FB),
    guitar: emoji(0x1F3B8),
    musicNote: emoji(0x266A),
    musicNotes: emoji(0x1F3B6),
    lightning: emoji(0x26A1, 0xFE0F),
    camera: emoji(0x1F4F8),
    tip: emoji(0x1F4B8),
    lock: emoji(0x1F512),
    phone: emoji(0x1F4F1),
    gift: emoji(0x1F381),
    pencil: emoji(0x270F, 0xFE0F),
    bell: emoji(0x1F514),
    question: emoji(0x2753),
    check: emoji(0x2705),
    cross: emoji(0x274C),
    coin: emoji(0x1FA99),
    skull: emoji(0x1F480),
    hourglass: emoji(0x23F3),
    magnifier: emoji(0x1F50D),
    refresh: emoji(0x1F504),
    test: emoji(0x1F9EA),
    star: emoji(0x1F31F),
    beer: emoji(0x1F37A),
    wave: emoji(0x1F44B),
    info: emoji(0x2139),
    robot: emoji(0x1F916)
};

export const REACTION_EMOJI = Object.freeze({
    fire: EMOJI.fire,
    heart: EMOJI.heart,
    clap: EMOJI.clap,
    drink: EMOJI.drink,
    rocket: EMOJI.rocket,
    diamond: EMOJI.diamond,
    crown: EMOJI.crown,
    money: EMOJI.cherryBlossom,
    star_power: EMOJI.star,
    meteor: emoji(0x2604, 0xFE0F),
    galaxy: emoji(0x1F30C),
    tomato: emoji(0x1F345),
    lightning: EMOJI.lightning,
    confetti: emoji(0x1F389),
    mic_drop: EMOJI.mic,
    ufo: emoji(0x1F6F8),
    dragon: emoji(0x1F409),
    spotlight_wave: EMOJI.wave,
    spotlight_heart: EMOJI.heart,
    spotlight_fire: EMOJI.fire,
    spotlight_mic: EMOJI.mic,
    spotlight_question: EMOJI.question,
    spotlight_truth: emoji(0x1F4AC),
    spotlight_shrug: emoji(0x1F937),
    spotlight_laugh: emoji(0x1F602),
    spotlight_skull: EMOJI.skull,
    spotlight_clap: EMOJI.clap,
    spotlight_micdrop: emoji(0x1F3A4),
    commentator_hot_take: emoji(0x1F9E0),
    commentator_callback: EMOJI.radio,
    commentator_vibe_check: emoji(0x1F4AF),
    commentator_wow: emoji(0x1F929)
});

export const getReactionEmoji = (type = '', fallback = EMOJI.heart) => {
    const key = String(type || '').trim().toLowerCase();
    return REACTION_EMOJI[key] || fallback;
};
