/**
 * Game Data Constants
 * Extracted from HostApp to prevent recreation on every render
 * 
 * Phase 1: Performance Optimization
 */

// Background music tracks for host
export const BG_TRACKS = [ 
    { name: "Lantern Circuit", url: "/audio/Lantern%20Circuit.mp3" },
    { name: "Retro Lounge", url: "https://beauross.com/wp-content/uploads/retro-lounge-389644.mp3" }, 
    { name: "Inspiring Synth", url: "https://beauross.com/wp-content/uploads/inspiring-motivation-synthwave-398285.mp3" }, 
    { name: "80s Retro", url: "https://beauross.com/wp-content/uploads/synthwave-80s-retro-background-music-400483.mp3" }, 
    { name: "Synth BG", url: "https://beauross.com/wp-content/uploads/synthwave-background-music-155701.mp3" }, 
    { name: "Classic 80s", url: "https://beauross.com/wp-content/uploads/2023/09/synthwave-80s-110045.mp3" }, 
    { name: "Chill", url: "https://cdn.pixabay.com/audio/2022/01/18/audio_d0a13f69d2.mp3" } 
];

// Sound effects for host control panel
export const SOUNDS = [ 
    { name: "Airhorn", icon: "fa-bullhorn", url: "https://beauross.com/wp-content/uploads/dj-airhorn-sound-39405.mp3" }, 
    { name: "Applause", icon: "fa-hands-clapping", url: "https://beauross.com/wp-content/uploads/1185_applause-02-1.mp3" }, 
    { name: "Fail", icon: "fa-thumbs-down", url: "https://beauross.com/wp-content/uploads/fail-trumpet-242645.mp3" }, 
    { name: "Fail 2", icon: "fa-circle-down", url: "https://beauross.com/wp-content/uploads/whistle-slide-down-02-350715-1-1.mp3" }, 
    { name: "Drumroll", icon: "fa-drum", url: "https://beauross.com/wp-content/uploads/1415_dhol-drums-01.mp3" }, 
    { name: "Crickets", icon: "fa-bug", url: "https://beauross.com/wp-content/uploads/cricket-chirps-331498.mp3" }, 
    { name: "Laugh", icon: "fa-face-laugh-squint", url: "https://beauross.com/wp-content/uploads/1825_laughter-01.mp3" }, 
    { name: "Rimshot", icon: "fa-drum-steelpan", url: "https://beauross.com/wp-content/uploads/ba-dum-tss-8279.mp3" }, 
    { name: "Cheer", icon: "fa-users", url: "https://beauross.com/wp-content/uploads/1194_crowd-cheering-01.mp3" }, 
    { name: "Boo", icon: "fa-thumbs-down", url: "https://beauross.com/wp-content/uploads/boo-6377.mp3" }, 
    { name: "Scratch", icon: "fa-compact-disc", url: "https://beauross.com/wp-content/uploads/1448_record-scratch-01.mp3" }, 
    { name: "My Way", icon: "fa-microphone", url: "https://beauross.com/wp-content/uploads/my-way-2008-remastered-made-with-Voicemod.mp3" }, 
    { name: "Sax Sexy", icon: "fa-music", url: "https://beauross.com/wp-content/uploads/sax-sexy-made-with-Voicemod.mp3" }, 
    { name: "Crowd Cheer", icon: "fa-hands-clapping", url: "https://beauross.com/wp-content/uploads/applause-crowd-cheer-made-with-Voicemod.mp3" }, 
    { name: "Boss Battle", icon: "fa-skull", url: "https://beauross.com/wp-content/uploads/boss-battle-music-made-with-Voicemod.mp3" }, 
    { name: "Cowbell", icon: "fa-bell", url: "https://beauross.com/wp-content/uploads/cowbell-made-with-Voicemod.mp3" }, 
    { name: "I Just Died", icon: "fa-heart", url: "https://beauross.com/wp-content/uploads/i-just-died-in-your-arms-made-with-Voicemod.mp3" }, 
    { name: "Hoa Hoa Hoa", icon: "fa-ghost", url: "https://beauross.com/wp-content/uploads/hoa-hoa-hoa-made-with-Voicemod.mp3" }, 
    { name: "Drowning", icon: "fa-water", url: "https://beauross.com/wp-content/uploads/sonic-drowning-made-with-Voicemod.mp3" } 
];

// Trivia questions for trivia game
export const TRIVIA_BANK = [
    { q: "Who is the 'Queen of Pop'?", correct: "Madonna", w1: "Lady Gaga", w2: "Beyonce", w3: "Britney Spears" },
    { q: "Which band wrote 'Bohemian Rhapsody'?", correct: "Queen", w1: "The Beatles", w2: "Led Zeppelin", w3: "Pink Floyd" },
    { q: "What is the best-selling album of all time?", correct: "Thriller", w1: "Back in Black", w2: "The Dark Side of the Moon", w3: "The Bodyguard" },
    { q: "Who sang 'I Will Always Love You' first?", correct: "Dolly Parton", w1: "Whitney Houston", w2: "Celine Dion", w3: "Mariah Carey" },
    { q: "Which artist released 'Purple Rain' as both an album and a movie?", correct: "Prince", w1: "David Bowie", w2: "George Michael", w3: "Lionel Richie" },
    { q: "Which group made 'Dancing Queen' a karaoke dance-floor staple?", correct: "ABBA", w1: "Fleetwood Mac", w2: "Blondie", w3: "The Go-Go's" },
    { q: "Which singer is widely nicknamed 'The Boss'?", correct: "Bruce Springsteen", w1: "Billy Joel", w2: "Bob Seger", w3: "John Mellencamp" },
    { q: "Which band released the karaoke anthem 'Don't Stop Believin'?", correct: "Journey", w1: "Foreigner", w2: "Boston", w3: "REO Speedwagon" },
    { q: "Which song is the classic internet 'Rickroll'?", correct: "Never Gonna Give You Up", w1: "Take On Me", w2: "Africa", w3: "Sweet Dreams" },
    { q: "Which artist's fans are commonly called Swifties?", correct: "Taylor Swift", w1: "Ariana Grande", w2: "Sabrina Carpenter", w3: "Olivia Rodrigo" },
    { q: "Which rapper starred in the movie '8 Mile'?", correct: "Eminem", w1: "Dr. Dre", w2: "Snoop Dogg", w3: "50 Cent" },
    { q: "Which artist made 'Single Ladies' a hand-wave anthem?", correct: "Beyonce", w1: "Rihanna", w2: "Alicia Keys", w3: "Ciara" },
    { q: "Which country icon is connected to Dollywood?", correct: "Dolly Parton", w1: "Reba McEntire", w2: "Shania Twain", w3: "Faith Hill" },
    { q: "Which instrument has 88 keys?", correct: "Piano", w1: "Guitar", w2: "Saxophone", w3: "Violin" },
    { q: "Which band made 'Mr. Brightside' a forever karaoke closer?", correct: "The Killers", w1: "The Strokes", w2: "Arctic Monkeys", w3: "Franz Ferdinand" },
    { q: "Which artist released 'Like a Prayer'?", correct: "Madonna", w1: "Cher", w2: "Cyndi Lauper", w3: "Janet Jackson" },
    { q: "Which band made 'Livin' on a Prayer' famous?", correct: "Bon Jovi", w1: "Aerosmith", w2: "Def Leppard", w3: "Poison" },
    { q: "Which singer made 'Rolling in the Deep' a modern belt-it-out anthem?", correct: "Adele", w1: "Kelly Clarkson", w2: "Pink", w3: "Sia" },
    { q: "Which pop star released 'Bad Romance'?", correct: "Lady Gaga", w1: "Katy Perry", w2: "Kesha", w3: "Miley Cyrus" },
    { q: "Which group sang 'I Want It That Way'?", correct: "Backstreet Boys", w1: "NSYNC", w2: "98 Degrees", w3: "Boyz II Men" },
    { q: "Which artist is known for the album 'Lemonade'?", correct: "Beyonce", w1: "Rihanna", w2: "Solange", w3: "Alicia Keys" },
    { q: "Which band released 'Smells Like Teen Spirit'?", correct: "Nirvana", w1: "Pearl Jam", w2: "Soundgarden", w3: "Alice in Chains" },
    { q: "Which song starts with the lyric 'Just a small town girl'?", correct: "Don't Stop Believin'", w1: "Sweet Caroline", w2: "Dream On", w3: "Piano Man" },
    { q: "Which artist made 'Uptown Funk' with Mark Ronson?", correct: "Bruno Mars", w1: "Pharrell Williams", w2: "Justin Timberlake", w3: "The Weeknd" },
    { q: "Which country star sang 'Friends in Low Places'?", correct: "Garth Brooks", w1: "Alan Jackson", w2: "Tim McGraw", w3: "George Strait" },
    { q: "Which singer made 'Man! I Feel Like a Woman!' a karaoke favorite?", correct: "Shania Twain", w1: "Faith Hill", w2: "Reba McEntire", w3: "LeAnn Rimes" },
    { q: "Which artist released 'Hotline Bling'?", correct: "Drake", w1: "Post Malone", w2: "Kendrick Lamar", w3: "J. Cole" },
    { q: "Which rock band is linked to the song 'Wonderwall'?", correct: "Oasis", w1: "Blur", w2: "Coldplay", w3: "Radiohead" },
    { q: "Which singer is famous for 'Piano Man'?", correct: "Billy Joel", w1: "Elton John", w2: "Paul Simon", w3: "James Taylor" },
    { q: "Which artist made 'Rocket Man' a signature song?", correct: "Elton John", w1: "David Bowie", w2: "Freddie Mercury", w3: "Phil Collins" },
    { q: "Which band released 'Hotel California'?", correct: "Eagles", w1: "Fleetwood Mac", w2: "The Doors", w3: "The Doobie Brothers" },
    { q: "Which artist sang 'Toxic'?", correct: "Britney Spears", w1: "Christina Aguilera", w2: "Jessica Simpson", w3: "Mandy Moore" },
    { q: "Which singer made 'Since U Been Gone' a karaoke power-pop staple?", correct: "Kelly Clarkson", w1: "Avril Lavigne", w2: "Pink", w3: "Hilary Duff" },
    { q: "Which band released 'Hey Ya!'?", correct: "OutKast", w1: "The Black Eyed Peas", w2: "Gnarls Barkley", w3: "N.E.R.D." },
    { q: "Which artist sang 'Truth Hurts'?", correct: "Lizzo", w1: "Doja Cat", w2: "Megan Thee Stallion", w3: "Cardi B" },
    { q: "Which singer released 'Blinding Lights'?", correct: "The Weeknd", w1: "Bruno Mars", w2: "Post Malone", w3: "Harry Styles" },
    { q: "Which artist made 'Watermelon Sugar'?", correct: "Harry Styles", w1: "Shawn Mendes", w2: "Niall Horan", w3: "Ed Sheeran" },
    { q: "Which artist is known for 'Drivers License'?", correct: "Olivia Rodrigo", w1: "Sabrina Carpenter", w2: "Billie Eilish", w3: "Tate McRae" },
    { q: "Which band made 'Seven Nation Army' a chant-ready anthem?", correct: "The White Stripes", w1: "The Black Keys", w2: "Kings of Leon", w3: "Arctic Monkeys" },
    { q: "Which song is strongly associated with Neil Diamond singalongs?", correct: "Sweet Caroline", w1: "Margaritaville", w2: "Tiny Dancer", w3: "Crocodile Rock" },
    { q: "Which artist sang 'Rehab'?", correct: "Amy Winehouse", w1: "Duffy", w2: "Adele", w3: "Lily Allen" },
    { q: "Which group released 'No Scrubs'?", correct: "TLC", w1: "Destiny's Child", w2: "En Vogue", w3: "SWV" },
    { q: "Which artist made 'Shake It Off'?", correct: "Taylor Swift", w1: "Carly Rae Jepsen", w2: "Katy Perry", w3: "Demi Lovato" },
    { q: "Which artist released 'Shape of You'?", correct: "Ed Sheeran", w1: "Sam Smith", w2: "Lewis Capaldi", w3: "James Arthur" },
    { q: "Which band made 'Africa' a karaoke comfort-song classic?", correct: "Toto", w1: "Chicago", w2: "Genesis", w3: "Styx" },
    { q: "Which singer is known for 'Girls Just Want to Have Fun'?", correct: "Cyndi Lauper", w1: "Pat Benatar", w2: "Belinda Carlisle", w3: "Bonnie Tyler" },
    { q: "Which artist made 'Old Town Road' a crossover hit?", correct: "Lil Nas X", w1: "Kane Brown", w2: "Post Malone", w3: "Nelly" },
    { q: "Which band released 'Basket Case'?", correct: "Green Day", w1: "Blink-182", w2: "Sum 41", w3: "The Offspring" },
    { q: "Which artist sang 'Hips Don't Lie'?", correct: "Shakira", w1: "Jennifer Lopez", w2: "Gloria Estefan", w3: "Nelly Furtado" },
    { q: "Which song is a signature Tina Turner anthem?", correct: "What's Love Got to Do with It", w1: "Respect", w2: "I Feel the Earth Move", w3: "If I Could Turn Back Time" }
];

// "Would You Rather" questions
export const WYR_BANK = [
    { q: "Sing every song in falsetto OR Sing every song like a death metal growl?", a: "Falsetto", b: "Death Metal" },
    { q: "Forget the lyrics to your favorite song OR Trip on stage every time you sing?", a: "Forget Lyrics", b: "Trip on Stage" },
    { q: "Have a voice like Mariah Carey but no rhythm OR Have moves like MJ but tone deaf?", a: "Voice", b: "Moves" },
    { q: "Only be able to sing Nickelback OR Only be able to sing Baby Shark?", a: "Nickelback", b: "Baby Shark" },
    { q: "Win every karaoke round OR Own the final encore singalong?", a: "Win Every Round", b: "Own The Encore" },
    { q: "Do a perfect Britney-style choreo routine OR Hit every high note dead-on?", a: "Perfect Choreo", b: "Perfect Notes" },
    { q: "Open the night with a power ballad OR Close the night with a rap verse?", a: "Open With Ballad", b: "Close With Rap" },
    { q: "Be the best duet partner in the room OR Be the best solo closer in the room?", a: "Best Duet Partner", b: "Best Solo Closer" },
    { q: "Sing one iconic 80s anthem OR one huge 2000s pop hit for the rest of the year?", a: "80s Anthem", b: "2000s Pop Hit" },
    { q: "Have the crowd scream your name before you start OR sing every chorus back at you?", a: "Crowd Intro", b: "Crowd Chorus" },
    { q: "Nail the key change OR nail the final pose?", a: "Key Change", b: "Final Pose" },
    { q: "Take a guaranteed standing ovation OR win the loudest applause meter all night?", a: "Standing Ovation", b: "Applause Meter" },
    { q: "Be remembered for one legendary note OR one legendary stage move?", a: "Legendary Note", b: "Legendary Move" },
    { q: "Sing only throwback anthems tonight OR only current chart songs tonight?", a: "Throwback Anthems", b: "Current Charts" },
    { q: "Get first pick of every song OR always get the ideal slot in the lineup?", a: "First Song Pick", b: "Best Lineup Slot" },
    { q: "Sing the first song of the night OR the last song of the night?", a: "First Song", b: "Last Song" },
    { q: "Perform with backup dancers OR a live fog machine?", a: "Backup Dancers", b: "Fog Machine" },
    { q: "Always get the perfect key OR always get the perfect tempo?", a: "Perfect Key", b: "Perfect Tempo" },
    { q: "Do a duet with your best friend OR a surprise duet with a stranger?", a: "Best Friend Duet", b: "Stranger Duet" },
    { q: "Sing a song everyone knows OR introduce the room to a deep cut?", a: "Everyone Knows It", b: "Deep Cut" },
    { q: "Have confetti on every chorus OR lasers on every high note?", a: "Confetti Chorus", b: "Laser High Notes" },
    { q: "Only sing 90s songs OR only sing 2010s songs?", a: "90s Songs", b: "2010s Songs" },
    { q: "Win by crowd volume OR win by perfect pitch?", a: "Crowd Volume", b: "Perfect Pitch" },
    { q: "Get a dramatic walk-on intro OR a dramatic slow-motion exit?", a: "Walk-On Intro", b: "Slow-Mo Exit" },
    { q: "Sing with a live band OR sing with a flawless karaoke track?", a: "Live Band", b: "Flawless Track" },
    { q: "Turn every song into country OR every song into disco?", a: "Country Version", b: "Disco Version" },
    { q: "Have the audience clap on beat OR sing every callback?", a: "Clap On Beat", b: "Sing Callbacks" },
    { q: "Be known for emotional ballads OR chaotic party songs?", a: "Ballads", b: "Party Songs" },
    { q: "Get one perfect spotlight moment OR three hilarious imperfect moments?", a: "Perfect Spotlight", b: "Funny Imperfect" },
    { q: "Sing without lyrics OR sing without hearing the backing track?", a: "No Lyrics", b: "No Backing Track" },
    { q: "Have a signature mic twirl OR a signature final bow?", a: "Mic Twirl", b: "Final Bow" },
    { q: "Perform a song you love badly OR a song you hate perfectly?", a: "Love It Badly", b: "Hate It Perfectly" },
    { q: "Only sing duets OR only sing solo songs?", a: "Only Duets", b: "Only Solo" },
    { q: "Get instant replay on TV OR a highlight reel after the night?", a: "Instant Replay", b: "Highlight Reel" },
    { q: "Have the host hype you up OR have the crowd chant your name?", a: "Host Hype", b: "Crowd Chant" },
    { q: "Sing a Disney villain song OR a 2000s breakup anthem?", a: "Villain Song", b: "Breakup Anthem" },
    { q: "Be the room's best harmony singer OR best hype person?", a: "Harmony Singer", b: "Hype Person" },
    { q: "Choose the next singer OR choose the next genre?", a: "Next Singer", b: "Next Genre" },
    { q: "Have every performance judged by applause OR by dance moves?", a: "Applause", b: "Dance Moves" },
    { q: "Sing in a costume OR sing with a prop?", a: "Costume", b: "Prop" },
    { q: "Only sing songs under three minutes OR only epic five-minute songs?", a: "Short Songs", b: "Epic Songs" },
    { q: "Get a perfect score from the app OR a perfect reaction from the crowd?", a: "App Score", b: "Crowd Reaction" },
    { q: "Start a room-wide singalong OR start a room-wide dance break?", a: "Singalong", b: "Dance Break" },
    { q: "Perform a song picked by the host OR a song picked by the audience?", a: "Host Pick", b: "Audience Pick" },
    { q: "Have unlimited song skips OR unlimited encore requests?", a: "Song Skips", b: "Encore Requests" },
    { q: "Sound amazing but stand still OR sound okay but own the stage?", a: "Amazing Voice", b: "Own The Stage" },
    { q: "Have one legendary duet OR one legendary solo performance?", a: "Legendary Duet", b: "Legendary Solo" },
    { q: "Sing the hardest song in the book OR the funniest song in the book?", a: "Hardest Song", b: "Funniest Song" },
    { q: "Let the crowd pick your song OR let the wheel pick your song?", a: "Crowd Pick", b: "Wheel Pick" },
    { q: "End with a mic drop OR end with a group bow?", a: "Mic Drop", b: "Group Bow" }
];
