import { lazy } from 'react';

const FlappyGame = lazy(() => import('../games/FlappyBird/Game'));
const BingoGame = lazy(() => import('../games/Bingo/Game'));
const PromptVoteGame = lazy(() => import('../games/PromptVote/Game'));
const VocalChallengeGame = lazy(() => import('../games/VocalChallenge/Game'));
const RidingScalesGame = lazy(() => import('../games/RidingScales/Game'));
const KaraokeBracketGame = lazy(() => import('../games/KaraokeBracket/Game'));
const TeamPongGame = lazy(() => import('../games/TeamPong/Game'));
const MusicalMomentsGame = lazy(() => import('../games/MusicalMoments/Game'));

export const GAME_REGISTRY = {
    'flappy_bird': FlappyGame, 
    'vocal_challenge': VocalChallengeGame,
    'riding_scales': RidingScalesGame,
    'bingo': BingoGame,
    'karaoke_bracket': KaraokeBracketGame,
    'team_pong': TeamPongGame,
    'musical_moments': MusicalMomentsGame,
    // Map multiple prompt-vote modes to the same cartridge.
    'trivia_pop': PromptVoteGame,
    'trivia_reveal': PromptVoteGame,
    'wyr': PromptVoteGame,
    'wyr_reveal': PromptVoteGame
};

// Comprehensive game metadata for unified UI
export const GAMES_META = [
    {
        id: 'doodle_oke',
        name: 'Doodle-oke',
        description: 'Sketch the lyric clue, let the room guess, then vote.',
        goal: 'Get the best guess and most votes.',
        howToPlay: 'Draw fast, reveal later, crowd picks a winner.',
        playModes: ['Round robin', 'Custom prompt'],
        icon: 'fa-solid fa-pen-ruler',
        category: 'voice',
        badge: 'Draw',
        color: 'cyan',
        hasConfig: true,
        needsVoice: true,
    },
    {
        id: 'flappy_bird',
        name: 'Pitch Runner',
        description: 'A forgiving voice runner where pitch trends steer through safe-lane gates.',
        goal: 'Sing higher, lower, or hold steady to pass gates while shields protect recovery.',
        howToPlay: 'Calibrate once, follow higher/lower/hold cues, and use Breath or shields when the room drifts.',
        playModes: ['Crowd mic', 'Solo singer'],
        icon: 'fa-solid fa-wave-square',
        category: 'voice',
        badge: 'Runner',
        color: 'cyan',
        hasConfig: true,
        needsVoice: true,
    },
    {
        id: 'vocal_challenge',
        name: 'Vocal Challenge',
        description: 'A SingStar-style target ribbon battle for crowd mode or spotlight singers.',
        goal: 'Lock onto target ribbons, stack streaks, and recover phrases with near matches.',
        howToPlay: 'Follow the target ribbon, hold the lane, and use Harmony Boost when the room needs a save.',
        playModes: ['Crowd battle', 'Spotlight turns'],
        icon: 'fa-solid fa-wave-square',
        category: 'voice',
        badge: 'Battle',
        color: 'pink',
        hasConfig: true,
        needsVoice: true,
    },
    {
        id: 'riding_scales',
        name: 'Riding Scales',
        description: 'A call-and-response voice game with replay safety and slower escalation.',
        goal: 'Push to higher rounds without the room getting punished for early misses.',
        howToPlay: 'Listen first, repeat second, and lean on replay saves to stay in it.',
        playModes: ['Crowd mode', 'Spotlight turns'],
        icon: 'fa-solid fa-music',
        category: 'voice',
        badge: 'Voice',
        color: 'cyan',
        hasConfig: true,
        needsVoice: true,
    },
    {
        id: 'team_pong',
        name: 'Team Pong',
        description: 'A left-vs-right vocal energy rally where chants charge saves and spikes.',
        goal: 'Keep the rally alive, build charge, and spike for team swings.',
        howToPlay: 'Chant with the crowd, Save before the rally drops, and Spike for +3.',
        playModes: ['Crowd chant', 'Left vs Right'],
        icon: 'fa-solid fa-table-tennis-paddle-ball',
        category: 'voice',
        badge: 'Chant',
        color: 'cyan',
        hasConfig: true,
        needsVoice: true,
    },
    {
        id: 'volley_orb',
        name: 'Volley Orb',
        description: 'Launch the lobby Vocal Rocket where crowd reactions and room-mic lift keep an orb airborne.',
        goal: 'Keep the orb alive, climb tiers, and push the room higher with vocal lift.',
        howToPlay: 'Audience phones add saves and combos while the Host room mic drives low-rumble launch and high-note lift.',
        playModes: ['Lobby relay', 'Vocal Rocket'],
        icon: 'fa-solid fa-volleyball',
        category: 'voice',
        badge: 'Orb',
        color: 'emerald',
        hasConfig: true,
        needsVoice: true,
    },
    {
        id: 'musical_moments',
        name: 'Musical Moments',
        description: 'Loop a famous song moment and let the room tap the hit while the Host mic scores the vocal lift.',
        goal: 'Nail the re-entry, beat drop, or big vocal moment with forgiving crowd timing.',
        howToPlay: 'Watch the loop, tap the target hit on phones, and sing the lift through the Host room mic.',
        playModes: ['Media loop', 'Tap + vocal'],
        icon: 'fa-solid fa-compact-disc',
        category: 'voice',
        badge: 'Moment',
        color: 'pink',
        hasConfig: true,
        needsVoice: true,
    },
    {
        id: 'trivia_pop',
        name: 'Trivia',
        description: 'Timed A/B/C/D rounds with fast scoreboard swings.',
        goal: 'Lock correct answers before timer hits zero.',
        howToPlay: 'Choose A, B, C, or D each round.',
        playModes: ['All players', 'Selected players'],
        icon: 'fa-solid fa-circle-question',
        category: 'brain',
        badge: 'Questions',
        color: 'amber',
        hasConfig: true,
        needsVoice: false,
    },
    {
        id: 'wyr',
        name: 'Would You Rather',
        description: 'Instant A vs B crowd votes for big room reactions.',
        goal: 'Force the room to pick a side.',
        howToPlay: 'Vote once, then watch the split.',
        playModes: ['All players', 'Selected players'],
        icon: 'fa-solid fa-scale-balanced',
        category: 'brain',
        badge: 'Voting',
        color: 'amber',
        hasConfig: true,
        needsVoice: false,
    },
    {
        id: 'bingo',
        name: 'Bingo',
        description: 'Mark live stage moments and chase line/corners/blackout.',
        goal: 'Complete the selected win pattern first.',
        howToPlay: 'Tap matching moments as they happen.',
        playModes: ['Classic', 'Mystery'],
        icon: 'fa-solid fa-table-cells-large',
        category: 'brain',
        badge: 'Marks',
        color: 'emerald',
        hasConfig: true,
        needsVoice: false,
    },
    {
        id: 'karaoke_bracket',
        name: 'Sweet 16 Bracket',
        description: 'Head-to-head elimination from singer Tight 15 match picks.',
        goal: 'Advance rounds and crown one champion.',
        howToPlay: 'Seed bracket, run matches, set winners.',
        playModes: ['Auto seed', '1v1 matches'],
        icon: 'fa-solid fa-trophy',
        category: 'social',
        badge: 'Tournament',
        color: 'rose',
        hasConfig: true,
        needsVoice: false,
    },
    {
        id: 'selfie_challenge',
        name: 'Selfie Challenge',
        description: 'Prompted selfie rounds with crowd voting and reveal.',
        goal: 'Capture the best shot and win votes.',
        howToPlay: 'Submit photo, then vote the wall.',
        playModes: ['Approval queue', 'Auto voting'],
        icon: 'fa-solid fa-camera-retro',
        category: 'social',
        badge: 'Photos',
        color: 'rose',
        hasConfig: true,
        needsVoice: false,
    },
];

export const GAME_CATEGORIES = {
    voice: {
        name: 'Voice Games',
        icon: 'VOICE',
        description: 'Games powered by singing and pitch detection',
    },
    brain: {
        name: 'Brain Games',
        icon: 'BRAIN',
        description: 'Trivia, voting, and strategy games',
    },
    social: {
        name: 'Social Games',
        icon: 'SOCIAL',
        description: 'Photo challenges and crowd interactions',
    },
};

export const getGameById = (id) => GAMES_META.find(g => g.id === id);
export const getGamesByCategory = (category) => GAMES_META.filter(g => g.category === category);
export const getGameCategories = () => Object.values(GAME_CATEGORIES);
