import FlappyGame from '../games/FlappyBird/Game';
import BingoGame from '../games/Bingo/Game';
import PromptVoteGame from '../games/PromptVote/Game';
import VocalChallengeGame from '../games/VocalChallenge/Game';
import RidingScalesGame from '../games/RidingScales/Game';
import KaraokeBracketGame from '../games/KaraokeBracket/Game';
import TeamPongGame from '../games/TeamPong/Game';

export const GAME_REGISTRY = {
    'flappy_bird': FlappyGame, 
    'vocal_challenge': VocalChallengeGame,
    'riding_scales': RidingScalesGame,
    'bingo': BingoGame,
    'karaoke_bracket': KaraokeBracketGame,
    'team_pong': TeamPongGame,
    // Map multiple prompt-vote modes to the same cartridge.
    'trivia_pop': PromptVoteGame,
    'trivia_reveal': PromptVoteGame,
    'wyr': PromptVoteGame,
    'wyr_reveal': PromptVoteGame
};

// Comprehensive game metadata for unified UI
export const GAMES_META = [
    {
        id: 'doodle_oke',
        name: 'Doodle-oke',
        description: 'Sketch the lyric clue, let the room guess, then vote.',
        goal: 'Get the best guess and most votes.',
        howToPlay: 'Draw fast, reveal later, crowd picks a winner.',
        playModes: ['Round robin', 'Custom prompt'],
        icon: 'fa-solid fa-pen-ruler',
        category: 'voice',
        badge: 'Draw',
        color: 'cyan',
        hasConfig: true,
        needsVoice: true,
    },
    {
        id: 'flappy_bird',
        name: 'Pitch Runner',
        description: 'Sing through note-height gates using your own calibrated range.',
        goal: 'Stay inside each note gap, string clean passes, and protect your lives.',
        howToPlay: 'Lock your range, match the target note line, and breathe when needed.',
        playModes: ['Crowd mic', 'Solo singer'],
        icon: 'fa-solid fa-wave-square',
        category: 'voice',
        badge: 'Voice',
        color: 'cyan',
        hasConfig: true,
        needsVoice: true,
    },
    {
        id: 'vocal_challenge',
        name: 'Vocal Challenge',
        description: 'Follow moving pitch targets with generous near-match scoring.',
        goal: 'Keep singing, stack streaks, and stay in the groove.',
        howToPlay: 'Match the note lane, and close hits still help.',
        playModes: ['Crowd mic', 'Solo singer'],
        icon: 'fa-solid fa-wave-square',
        category: 'voice',
        badge: 'Voice',
        color: 'pink',
        hasConfig: true,
        needsVoice: true,
    },
    {
        id: 'riding_scales',
        name: 'Riding Scales',
        description: 'Repeat growing scale patterns with replays and softer miss rules.',
        goal: 'Push to higher rounds without the game getting mean.',
        howToPlay: 'Hear the pattern, sing it back, use replays to recover.',
        playModes: ['Crowd mode', 'Spotlight turns'],
        icon: 'fa-solid fa-music',
        category: 'voice',
        badge: 'Voice',
        color: 'cyan',
        hasConfig: true,
        needsVoice: true,
    },
    {
        id: 'team_pong',
        name: 'Team Pong',
        description: 'Split the room into left vs right and keep the rally alive.',
        goal: 'Build the longest rally streak as a team.',
        howToPlay: 'Tap your paddle on phone to return the ball.',
        playModes: ['All players', 'Crowd teams'],
        icon: 'fa-solid fa-table-tennis-paddle-ball',
        category: 'social',
        badge: 'Teams',
        color: 'cyan',
        hasConfig: true,
        needsVoice: false,
    },
    {
        id: 'trivia_pop',
        name: 'Trivia',
        description: 'Timed A/B/C/D rounds with fast scoreboard swings.',
        goal: 'Lock correct answers before timer hits zero.',
        howToPlay: 'Choose A, B, C, or D each round.',
        playModes: ['All players', 'Selected players'],
        icon: 'fa-solid fa-circle-question',
        category: 'brain',
        badge: 'Questions',
        color: 'amber',
        hasConfig: true,
        needsVoice: false,
    },
    {
        id: 'wyr',
        name: 'Would You Rather',
        description: 'Instant A vs B crowd votes for big room reactions.',
        goal: 'Force the room to pick a side.',
        howToPlay: 'Vote once, then watch the split.',
        playModes: ['All players', 'Selected players'],
        icon: 'fa-solid fa-scale-balanced',
        category: 'brain',
        badge: 'Voting',
        color: 'amber',
        hasConfig: true,
        needsVoice: false,
    },
    {
        id: 'bingo',
        name: 'Bingo',
        description: 'Mark live stage moments and chase line/corners/blackout.',
        goal: 'Complete the selected win pattern first.',
        howToPlay: 'Tap matching moments as they happen.',
        playModes: ['Classic', 'Mystery'],
        icon: 'fa-solid fa-table-cells-large',
        category: 'brain',
        badge: 'Marks',
        color: 'emerald',
        hasConfig: true,
        needsVoice: false,
    },
    {
        id: 'karaoke_bracket',
        name: 'Sweet 16 Bracket',
        description: 'Head-to-head elimination from singer Tight 15 match picks.',
        goal: 'Advance rounds and crown one champion.',
        howToPlay: 'Seed bracket, run matches, set winners.',
        playModes: ['Auto seed', '1v1 matches'],
        icon: 'fa-solid fa-trophy',
        category: 'social',
        badge: 'Tournament',
        color: 'rose',
        hasConfig: true,
        needsVoice: false,
    },
    {
        id: 'selfie_challenge',
        name: 'Selfie Challenge',
        description: 'Prompted selfie rounds with crowd voting and reveal.',
        goal: 'Capture the best shot and win votes.',
        howToPlay: 'Submit photo, then vote the wall.',
        playModes: ['Approval queue', 'Auto voting'],
        icon: 'fa-solid fa-camera-retro',
        category: 'social',
        badge: 'Photos',
        color: 'rose',
        hasConfig: true,
        needsVoice: false,
    },
];

export const GAME_CATEGORIES = {
    voice: {
        name: 'Voice Games',
        icon: 'VOICE',
        description: 'Games powered by singing and pitch detection',
    },
    brain: {
        name: 'Brain Games',
        icon: 'BRAIN',
        description: 'Trivia, voting, and strategy games',
    },
    social: {
        name: 'Social Games',
        icon: 'SOCIAL',
        description: 'Photo challenges and crowd interactions',
    },
};

export const getGameById = (id) => GAMES_META.find(g => g.id === id);
export const getGamesByCategory = (category) => GAMES_META.filter(g => g.category === category);
export const getGameCategories = () => Object.values(GAME_CATEGORIES);
