import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { test } from 'vitest';

const source = readFileSync('src/apps/Mobile/SingerApp.jsx', 'utf8');

test('audience app exposes run-of-show release-window controls for crowd and co-host voters', () => {
  assert.match(source, /getRunOfShowOperatorRole/);
  assert.match(source, /getRunOfShowReleaseWindowTally/);
  assert.match(source, /isRunOfShowReleaseWindowVotingOpen/);
  assert.match(source, /getRunOfShowReleaseWindowRemainingMs/);
  assert.match(source, /const canSeeAudienceReleaseWindow = useMemo/);
  assert.match(source, /const castRunOfShowReleaseVote = async/);
  assert.match(source, /castRunOfShowReleaseWindowVote/);
  assert.match(source, /castAudienceDecisionVote/);
  assert.match(source, /buildReleaseWindowFromAudienceDecision/);
  assert.match(source, /choiceAudienceDecisionIds/);
  assert.match(source, /Co-Host Song Face-Off/);
  assert.match(source, /Audience Song Face-Off/);
  assert.match(source, /Co-Host Slot Fill/);
  assert.match(source, /Audience Slot Fill/);
  assert.match(source, /Co-hosts are helping steer what happens next\./);
  assert.match(source, /Pick one\. Host confirms the winner\./);
  assert.match(source, /Pick who should fill this slot\. Host confirms\./);
  assert.match(source, /Promoted Co-Host/);
  assert.match(source, /getAudienceSongArtworkUrl/);
  assert.match(source, /max-w-\[26rem\]/);
  assert.match(source, /COHOST_SIGNAL_OPTIONS/);
  assert.match(source, /const canUseCoHostQuickSignals = useMemo/);
  assert.match(source, /const sendCoHostQuickSignal = async/);
  assert.match(source, /sendRoomOperatorSignal/);
  assert.match(source, /type: audioArea \? 'audio_attention' : meta\.id/);
  assert.match(source, /respondToRoomCoHostInvite/);
  assert.match(source, /leaveRoomCoHostRole/);
  assert.match(source, /data-feature-id="cohost-invitation"/);
  assert.match(source, /data-feature-id="cohost-quick-signals"/);
  assert.match(source, /Tell Host/);
  assert.match(source, /No live performance\. Signals still carry a timestamp\./);
  assert.match(source, /Private operational notes are timestamped and tied to the live performance when one is up\./);
  assert.match(source, /const audioCoHostSignals = useMemo/);
  assert.match(source, /const currentPerformanceSignalContext = useMemo/);
  assert.match(source, /formatElapsedClock/);
  assert.match(source, /COHOST_SIGNAL_COOLDOWN_MS/);
  assert.match(source, /canSeeAudienceReleaseWindow && isAudienceSongFaceOffDecision/);
  assert.match(source, /const isAudienceSlotFillDecision = audienceReleaseSubjectType === 'slot_fill_choice';/);
  assert.match(source, /const isAudienceOneMinuteMicDecision = audienceReleaseSubjectType === 'continue_or_rotate';/);
  assert.match(source, /const isAudienceSkipPerformanceDecision = audienceReleaseSubjectType === 'skip_performance';/);
  assert.match(source, /performanceAudienceDecisionPresentation/);
  assert.match(source, /isAudienceOneMinuteMicDecision \? 'Keep Singing'/);
  assert.match(source, /Next Singer must win clearly; a tie keeps the singer/);
  assert.match(source, /Next Singer needs 55%. A tie keeps the singer/);
  assert.match(source, /isAudiencePerformanceProgressionDecision \? 'text-2xl'/);
  assert.match(source, /isAudiencePerformanceProgressionDecision \? 'text-lg font-black'/);
  assert.match(source, /Crowd Rescue Vote/);
  assert.match(source, /choiceSublines\?\.slot_scene/);
  assert.match(source, /fa-forward-step/);
  assert.match(source, /choiceLabels\?\.slot_scene/);
  assert.match(source, /choiceDetails\?\.keep_queue_moving/);
  assert.match(source, /You voted for \$\{voteLabel\}\./);
  assert.match(source, /totalVotes \|\| 0\} total/);
  assert.match(source, /Host confirms the winner after voting closes\./);
  assert.match(source, /audienceReleasePanelProminent/);
  assert.match(source, /Live vote - tap now/);
  assert.match(source, /audienceReleasePanelProminent && !isAudiencePerformanceProgressionDecision/);
  assert.match(source, /data-audience-release-window-panel/);
  assert.match(source, /data-audience-release-choice-card="slot_scene"/);
  assert.match(source, /data-audience-release-choice-card="keep_queue_moving"/);
  assert.match(source, /audienceReleaseChoiceCounts/);
  assert.match(source, /getAudienceReleaseChoicePct/);
  assert.match(source, /authCurrentUid: isQaAudienceFixture \? '' : auth\.currentUser\?\.uid/);
  assert.match(source, /authReadyUid: isQaAudienceFixture \? '' : authReadyUid/);
});
